import 'catalog_sanitize.dart';
import 'models.dart';

/// Catalog seed parity with Kotlin `DefaultChannels` SEED_VERSION 26.
class DefaultChannels {
  static const seedVersion = 31;

  /// Wrong upload formerly labeled مابي أنام; replaced by بنيتي الحبوبة.
  static const _retiredKidsMusicVideoId = 'ISSlEZyIRFw';

  /// Rotating YouTube live IDs that crash in the kid player when the stream ends.
  static const retiredLiveVideoIds = {
    'wawzF8i5yAo',
    '3eAQvIImyTM',
    'tuOo0oPuc2Y',
    'Rs7St51oDDc',
  };

  static const _spacetoonUploadsPlaylist = 'UUuQKih3Ac3NABADQKQdeV6A';
  static const _dawoodHubPlaylist = 'PLKhm8Z5pXdOUWVTnTojfHw_Cr7Ac-HLyR';
  static const _numberblocksSeason1Playlist =
      'PL9swKX1PviEr9UfByZqJYiN8KX3AXqyXm';
  /// Games For Kids Hub — Dad & Olivia Play (calm Minecraft builds only).
  static const _dadOliviaMinecraftPlaylist =
      'PLCGF5P4ZzZ6d2S5-RVKKkFp-wLZk-uKP9';

  static const retiredChannelIds = {
    'arabic_cartoons',
    'learn_arabic',
    'islamic_kids',
    'playtime',
    'fulla',
    'toyor_jana',
    'disney_songs_ar',
    'live_quran',
    'dawood_juz_amma',
    'dawood_juz_amma_plain',
    'dawood_juz_amma_repeat',
    'dawood_juz_amma_selection',
    'dawood_juz_amma_memorize',
    'dawood_juz_amma_3d',
    'dawood_stories',
    'dawood_teaches_me',
    'dawood_and_me',
    'dawood_secrets_industry',
    'dawood_quranic_games',
    'dawood_quran_quiz',
    'dawood_tabarak',
    'dawood_tabarak_plain',
    'dawood_tabarak_memorize',
    'dawood_juz_28',
    'dawood_juz_27',
    'dawood_juz_26',
  };

  static List<ContentChannel> seed() {
    final channels = [
        _channel(
          id: 'omar_hana',
          title: 'Omar & Hana',
          order: 0,
          color: 0xFF66BB6A,
          playlist: _uploadsOf('UC178EmfQAV3OT-UpuO6WUMg'),
          videos: [
            _yt('T6ggVnk1JZg', 'Omar & Hana 15 Minutes Song'),
            _yt('iJtM9bzScJY', 'Omar & Hana — Dua & Salah (Acapella)'),
            _yt('HvzYeFB0lB4', 'Breakfasting — Omar & Hana'),
            _yt('AkSrzSwK2wE', 'Omar & Hana Arabic — Please Come Home Dad'),
            _yt('T5b1d3xvh3c', 'Omar & Hana Arabic — مجموعة رسوم دينية'),
            _yt('V9bIdfyiQYQ', 'Omar & Hana Arabic — مجموعة حلقات'),
            _yt('_YMsrKhUnPs', 'Salam Scientist — Omar & Hana'),
            _yt('icd_EkXP1Eo', "Dad's Magical Dish — Omar & Hana"),
            _yt('oAKrc9esltY', 'Alhamdulillah, Bismillah, Insha Allah 🥰😍 | NO INSTRUMENTS 🎶 | Omar & Hana English'),
            _yt('oYKeA8PnNDc', 'Masjid Al-Aqsa 😍 | Islamic Series & Songs For Kids | Omar & Hana English'),
            _yt('mMovpU-UALI', 'Omar & Hana Learn Islam Together 😍🥰 | Islamic Series & Songs For Kids | English'),
            _yt('CHrw1Lquv68', 'May Allsh Bless You 😍🥰 | Islamic Series & Songs For Kids | Omar & Hana English'),
            _yt('oC2NXQGwx6w', 'Papa with The Kids 😊 | Islamic Series & Songs For Kids | Omar & Hana English'),
            _yt('WAy9-yo4mYM', 'Omar & Hana 😍🏖️🧁| 45 Minutes NO INSTRUMENTS | Omar & Hana English'),
            _yt('AaRHqi6qv24', 'Get Ready with Miss Laila 😍 | Islamic Series & Songs For Kids | Omar & Hana English'),
            _yt('kQShJ-VMADo', 'Let\'s Clean Up 😍 | Islamic Series & Songs For Kids | Omar & Hana English'),
            _yt('KJWInx7vmwc', 'Mama & Her Phone Again!? 😤 | Islamic Series & Songs For Kids | Omar & Hana English'),
            _yt('DiJDhPOuwpM', 'Thankyou Omar 😊 | Islamic Series & Songs For Kids | Omar & Hana English'),
          ],
        ),
        _channel(
          id: 'mini_muslim',
          title: 'Mini Muslim',
          order: 1,
          color: 0xFF26A69A,
          playlist: _uploadsOf('UCIDYe6rgdROl77DDevNIcPA'),
          videos: [
            _yt('4VpiuY_C5Ok', 'Ramadan Around The World — MiniMuslims'),
            _yt('vB3ffnqdNVs', 'Islamic Songs for Kids (45 min) — MiniMuslims'),
            _yt('WyxekrpqcEQ', 'Islamic Songs for Kids (30 min) — MiniMuslims'),
            _yt('8aABPaYMpUs', "Let's Count To 10 — MiniMuslims"),
            _yt('sWk1Xyqv19Y', 'Mawlid Song — Salawatun Tayyibatun'),
            _yt('HgREL4X7eUg', 'The Ants Go Marching — MiniMuslims'),
            _yt('mVGnpSthYZQ', 'Mawlaya Burdah — MiniMuslims'),
            _yt('L6b5cjGhVEo', 'Allahumma Salli (Fiyyashiyya) ☀️ New Song from MiniMuslims!'),
            _yt('nNhaFbvqah4', 'Islamic Songs for Kids 💫 Allahumma Salli (Fiyyashiyya) ☀️ MiniMuslims & Raef'),
            _yt('UQ8-EyYvzfc', 'A MiniMuslims version of a classic...this Saturday 👀  #fiyyashiyya'),
            _yt('ideZbpZREtk', 'Never forget to say la ilaha ill Allah ☝🏻'),
            _yt('pN7oDfL-KgY', 'Around the world, our hearts beat as one✊🏻❤️'),
            _yt('mt12SffLgx8', 'Allah Made The World 🌍'),
            _yt('8oIH6dQxbp4', 'This olive tree is a symbol of the resilience of the Palestinian people 🌱 🫒  #miniMuslims'),
            _yt('DWstnTnFGWA', 'Surat Al-Ma\'un سورة الماعون ☀️ MiniMuslims'),
            _yt('A-u5BIctpwo', 'Jamal learning the prophetic characteristic of resilience, the heart of "Hasbi Allah wa…'),
            _yt('VJbmL7TYwo0', 'Maryam, Sarah, and Jamal continue their quest to save their island, this time stopping…'),
          ],
        ),
        _channel(
          id: 'dawood',
          title: 'داوود',
          order: 2,
          color: 0xFF00897B,
          playlist: _dawoodHubPlaylist,
          followUploads: true,
          videos: const [],
        ),
        _channel(
          id: 'kids_music',
          title: 'Kids Music',
          order: 3,
          color: 0xFFEC407A,
          sourceType: SourceType.youtubeVideoList,
          videos: [
            _yt('wyOJfLSeZIE', 'بابا فين — Free Baby (Music Video)'),
            _yt('5wnNBQAkc-A', 'ماما جابت بيبي — جنى مقداد | طيور الجنة'),
            _yt(
              'qn3ITODjLiw',
              'بنيتي الحبوبة — حلا الترك و مشاعل',
            ),
            _yt(
              '03X3iys-Rcs',
              'أغنية آيس كريم — ثعلوب والفواكه | أسرتنا',
            ),
            _yt(
              'Gmhk7mWG050',
              'في منزل أنثى السنجاب — أسرتنا',
            ),
            _yt(
              'Pf1Y0JtfMPU',
              'أنشودة الخضروات — أسرتنا',
            ),
            _yt(
              'WqzwrbzSqyY',
              'أغنية الكواكب — أسرتنا',
            ),
            _yt(
              'wK-YBukZUuU',
              'كوكسينو والعنكبوت — أسرتنا',
            ),
            _yt(
              'NWcs3bZ0fSM',
              'رمضان جانا — أسرتنا',
            ),
            _yt(
              'XE4qklLOokQ',
              'أنا البندورة الحمراء — طيور الجنة',
            ),
            _yt(
              'ZUCS_cR9cY8',
              'ساعة من أغاني أسرتنا — بدون إيقاع',
            ),
            _yt('-oKjZlrsJlQ', 'ساعة كاملة من أجمل أغاني قناة أسرتنا للأطفال'),
            _yt('w0V8Q6CVc7g', 'جميع أغاني ثعلوب - قناة أسرتنا'),
            _yt('l90IBX0wqOE', 'مجموعة من اجمل اغاني الاطفال  | قناة أسرتنا'),
            _yt('24bcBAORGgE', 'دق دق من بالباب؟ 🦊 أغنية الثعلب المكار | أغاني الأطفال - قناة أسرتنا'),
            _yt('LaNbV2GI4yE', '🦊أغنية  ثعلوب دو دو دو 🎵 | أغنية عائلة ثعلوب للأطفال | أغاني الأطفال العربية | Baby Fox…'),
            _yt('_MAKSeMT8Mo', 'زرعنا جزرة في وسط البستان |  قناة أسرتنا'),
            _yt('mecMSY7uak4', 'لا تفتح الباب لثعلوب! 🚪 أجمل أغاني أسرتنا للأطفال'),
            _yt('h1sXuODG5_w', 'أغنية الذئب والعنزات السبع  | قناة أسرتنا -  أغاني أطفال'),
            _yt('7azibRvj9YQ', 'أغنية ثعلوب الغشاش  | أغاني الأطفال |  قناة أسرتنا'),
            _yt('R5uVr6oIyrI', 'دق دق الباب! ثعلوب والأكل غير الصحي | أغنية أطفال تعليمية | أسرتنا'),
          ],
        ),
        _channel(
          id: 'spacetoon',
          title: 'Spacetoon أناشيد',
          order: 14,
          color: 0xFF5C6BC0,
          sourceType: SourceType.youtubeVideoList,
          videos: [
            _yt('-_Kz-hseLkc', 'كتاب الله'),
            _yt('s7FQXvhwm40', 'كتابُ الله'),
            _yt('mJMigyCh-I8', 'أغنية الكتاب'),
            _yt('YoAU-tciuVs', 'يا طيبة — المدينة المنورة'),
            _yt('2h6Y8k8fNS4', 'هيا للمسجد لنصلي'),
            _yt('g7LjhyO7CEw', 'رمضان أقبل طيباً'),
            _yt('INZMVhnVlRM', 'أهلاً رمضان يا شهر الإحسان'),
            _yt('BojfVe5G6GM', 'هلال رمضان — يوسف إسلام'),
            _yt('Jh4gl0obMK0', 'رمضان 2020 — أطل الفجر بالبشر'),
            _yt('dB95J8Pa49c', 'أغنية بداية أنا وأختي'),
            _yt('o9xR7JcU2iw', 'فلفول — أغنية السلطة'),
            _yt('krYQGcQ3o0U', 'جميع أغاني الأشكال الهندسية'),
            _yt('fxZE5hOMyi4', 'أكثر من 30 دقيقة — أروع أغاني سبيستون'),
            _yt('_CB9Dv2-hxA', 'سبيستون | بابار فيل | شارة العمل'),
            _yt('2w_dzCWVS90', 'أغنية ري بون بون - سبيس تون 🎵 Rebonbon - Spacetoon'),
            _yt('A698snupPJs', 'أغنية سبيستونات - على أدي - سبيستون 🎵 Spacetoon'),
            _yt('NP5Ex1bCh-o', 'Spacetoon - Falfool - Egg Song | سبيستون - فلفول - أغنية البيضة'),
            _yt('JOz8CVQjTuA', 'سبيستون - أغنية شارة القناص'),
            _yt('BYmcd8I4qcQ', 'أغنية بداية عهد الأصدقاء - سبيستون 🎵 Spacetoon'),
            _yt('YORQ3vgmLVA', 'Spacetoon | سبيستون - أغنية فصل الصيف شمس سطعت'),
            _yt('eFDwd9AurQQ', 'سبيستون - أغنية حياتي غيرل | Spacetoon - HayatiGirl Song'),
            _yt('VGuSIeV5ZLw', 'سبيستون | نجمة الطبخ | شارة العمل 🎶'),
            _yt('18-WQX19Aco', 'أغنية بداية دري لاند - سبيستون 🎵 Tanken DRILAND Song ٍSpacetoon'),
          ],
        ),
        _channel(
          id: 'moda_modi',
          title: 'مودا مودي',
          order: 15,
          color: 0xFF7E57C2,
          sourceType: SourceType.youtubeVideoList,
          videos: [
            _yt('V2upg7iZvT0', 'مودا مودي — وأتى رمضان'),
            _yt('_SdwG5nE0Ik', 'مودا مودي — رمضان عاد'),
            _yt('7DUiKe_UneA', 'عائلة مودا مودي — رمضان تجلّى'),
            _yt('8cRwwgOzHF4', 'أغنية عيد الفطر من مودا مودي'),
            _yt('iIg9QBsd-Rw', 'أنا مودو — مودا مودي | سبيستون'),
            _yt('AWHJRkWISgs', 'هل تعلمين ماذا فعلت اليوم — مودا مودي'),
            _yt('zYhbSoxUOIY', 'دعونا نبني — مودا مودي | سبيستون'),
            _yt('hCFI7oi6XRc', 'دمتي أمي دمت يا أبي — مودا مودي'),
            _yt('4FIejnevzOk', 'مودا مودي - كل يوم الجزء الثاني'),
            _yt('LpOB_vggVNo', 'Mooda Moody - Spacetoon - مودا مودي - الغيرة'),
            _yt('OXmciFtpTx8', 'My Family Mooda Moody - عائلتي - موودا مودي - سبيس تون'),
            _yt('JZcnyuMOS4g', 'سبيستون | مودا مودي | أغنية كفى حرباً 💔'),
            _yt('4nQtDfihl8s', 'مودا مودي العودة إلى المدرسة - سبيستون'),
            _yt('wRMxxhJG8qs', 'سبيستون | عائلة مودا مودي | الحلقة 11 | صندوق الأحلام'),
            _yt('rpQjTA-oBkg', 'سبيستون | عائلة مودا مودي | الحلقة 10 | أين الصندوق؟!'),
            _yt('j3TMwAZHUT0', 'سبيستون | Spacetoon - مودا مودي - الحجر الصحي'),
            _yt('mH0rjbVIId0', 'سبيستون | Spacetoon - مودا مودي - أغنية بائع المثلجات'),
            _yt('ccs-FJZvMRs', 'سبيستون | مودا مودي | يا موطن القلبِ يا أبتِ | أغنية يوم الأب ✨'),
          ],
        ),
        _channel(
          id: 'smarta',
          title: 'سمارتا وحقيبتها العجيبة',
          order: 16,
          color: 0xFF42A5F5,
          sourceType: SourceType.youtubeVideoList,
          videos: [
            _yt('USLdtIWQrLU', 'سمارتا — الحلقة 1'),
            _yt('efHkhsi675M', 'سمارتا — الحلقة 2'),
            _yt('nP-F7A54oVc', 'سمارتا — الحلقة 3'),
            _yt('xIFNnxZD5IQ', 'ساعة من المغامرات — المجموعة الأولى'),
            _yt('Ui2P60B2WJE', 'مجموعة الحلقات الثالثة'),
            _yt('rf8FgLed_E8', 'مجموعة الحلقات الرابعة'),
            _yt('YgXdgZ2Wd0I', 'مجموعة الحلقات الخامسة'),
            _yt('5xftaiEK_7Y', 'مجموعة الحلقات السادسة'),
            _yt('nPBlRc5heBc', 'مجموعة الحلقات السابعة'),
            _yt('wcIW_tbTB3M', 'مجموعة الحلقات الثامنة'),
            _yt('kJULJaJjD4M', 'مجموعة الحلقات العاشرة'),
            _yt('KcB3gNtM8NY', 'سبيستون | ساعة من مغامرات سمارتا وحقيبتها العجيبة - المجموعة االثانية'),
            _yt('9nEE_WQNP3E', 'سبيستون - سمارتا وحقيبتها العجيبة الحلقة 4 | Spacetoon - Smarta and her Magic Bag Ep 4'),
            _yt('q_iaBV6b5YM', 'سبيستون | سمارتا وحقيبتها العجيبة_مجموعة الحلقات التاسعة'),
            _yt('cQztjZxi5ho', 'سبيستون - سمارتا وحقيبتها العجيبة الحلقة 5 | Spacetoon - Smarta and her Magic Bag Ep 5'),
            _yt('d5Uc5v8X4yE', 'سبيستون - سمارتا وحقيبتها العجيبة الحلقة 14| Spacetoon - Smarta and her Magic Bag Ep 14'),
            _yt('nbf0lLaAQuM', 'سبيستون - سمارتا وحقيبتها العجيبة الحلقة 18 | Spacetoon - Smarta and her Magic Bag Ep 18'),
            _yt('0nOQOgXr9Yw', 'سبيستون - سمارتا وحقيبتها العجيبة الحلقة 28 | Spacetoon - Smarta and her Magic Bag Ep 28'),
            _yt('9rT5HhM0viQ', 'سبيستون - سمارتا وحقيبتها العجيبة الحلقة 12 | Spacetoon - Smarta and her Magic Bag Ep 12'),
            _yt('AdMdiSDhyo0', 'سبيستون - سمارتا وحقيبتها العجيبة الحلقة 33 | Spacetoon - Smarta and her Magic Bag Ep 33'),
            _yt('Nbv1UiQpvkw', 'كرتون للأطفال عن مدينة الملاهي | سمارتا وحقيبتها السحرية | تعلم الألوان'),
          ],
        ),
        _channel(
          id: 'adam_mishmish',
          title: 'Adam & Mishmish',
          order: 18,
          color: 0xFFFFA726,
          sourceType: SourceType.youtubeVideoList,
          videos: [
            _yt('FurzMF0L6QI', 'Animal Sounds Songs (68 min) — Adam & Mishmish'),
            _yt('docDippkI-Q', 'Farm Animal Songs — Adam & Mishmish'),
            _yt('etAPDF2i9s0', 'Arabic Letters with Animals — Adam & Mishmish'),
            _yt('Sp85Q-qiqQw', 'أغاني عربية للأطفال 60 دقيقة — آدم ومشمش'),
            _yt('w67-oHQNBVA', 'الأغاني المفضلة 60 دقيقة — آدم ومشمش'),
            _yt('auSSr85LDbE', 'أغاني جديدة ممتعة — آدم ومشمش'),
            _yt('IDP3sV9ZMEc', 'أغنية الرياضة والحركة — آدم ومشمش'),
            _yt('dkLTDe6sgB4', 'أغاني الحيوانات مع نبيل النحلة 🐝🦁 | آدم ومشمش'),
            _yt('ffsW1qQjioc', 'أغنية الحروف البطيئة للأطفال 🐣✏️ | آدم ومشمش'),
            _yt('J2ZiGiuFi2o', 'طبقي المفضل - قصة محكية والمزيد 15 دقيقة 🍽️🥗 | آدم ومشمش'),
            _yt('TwIa3BeuT4Q', 'أغنية كرة القدم للأطفال ⚽🏆 | آدم ومشمش'),
            _yt('xzu0bg18cfA', 'كيف نقول؟ - الألوان والمزيد 12 دقيقة 🎨🌈 | آدم ومشمش'),
            _yt('JI96qVO4P_Q', 'أغاني الأساسيات مع نبيل النحلة 🐝🎶 | آدم ومشمش'),
            _yt('tj0agw2KMBs', 'ألبوم الصور - قصة محكية والمزيد 31 دقيقة 📸🌿 | آدم ومشمش'),
            _yt('T4aeJwtQ7X4', 'أغنية رقصة التجمد للأطفال 🧊🕺 | آدم ومشمش'),
            _yt('2LaIBgvzIRY', 'أغنية الحركات للأطفال 🕺👯 | آدم ومشمش'),
            _yt('Rb9uHgiIxhU', 'أغنية الرياضة للأطفال 🏃‍♂️⚽ | آدم ومشمش'),
            _yt('lF8MN1_xDEQ', 'أغنية الكواكب للأطفال 🌍🪐 | آدم ومشمش'),
            _yt('zr9RaXlMEP8', 'الحروف العربية للأطفال ✏️📚 | آدم ومشمش'),
          ],
        ),
        _channel(
          id: 'zakaria',
          title: 'Zakaria',
          order: 19,
          color: 0xFF29B6F6,
          sourceType: SourceType.youtubeVideoList,
          videos: [
            _yt('LocumA_zI0c', 'Learn Colors with Cars — Zakaria'),
            _yt('sGw7Fs7oRvw', 'Vehicle Names in Arabic — Zakaria'),
            _yt('XCp_1eTPnrM', 'Arabic Numbers 1–10 — Zakaria'),
            _yt('0MGqhiLQbxI', 'Write Arabic Alphabet أ–ص — Zakaria'),
            _yt('5v7A2AXzCY0', 'Write Arabic Alphabet ض–ي — Zakaria'),
            _yt('USW8_gV_Hnw', 'Colors with Street Vehicles — Zakaria'),
            _yt('So5y8Sy8R6Y', 'Street Vehicles in Arabic — Zakaria'),
            _yt('_pUf4xdBqxA', 'Counting with Cars 1–10 — Zakaria'),
            _yt('x8BTd1ytd2k', 'أغنية الصرصور الغدار | أنشودة مضحكة للأطفال عن النظافة - تعلم  مع زكريا'),
            _yt('OQs8g1DN55o', 'أغنية الحروف الأبجدية العربية للأطفال بدون موسيقى | أنشودة حروف الهجاء – نشيد تعليم الحروف'),
            _yt('gr3XKopIsVA', 'واحد اثنان ثلاثة أنشودة الأرقام بدون ايقاع | تعليم الأرقام من ١ إلى ١٠ للأطفال - أناشيد…'),
            _yt('HO08HGnIlxA', 'أنشودة الفأر 🐭 | فأر دخل الدار 😱 | أغنية مضحكة وتعليمية للأطفال بدون موسيقى'),
            _yt('cFU6B07-34w', 'مجموعة أناشيد الحيوانات والحشرات للأطفال | البعوضة والصرصور والذئب وزيكو والخروف 🐺🐱🐑🦟'),
            _yt('OF4nMJ8icWg', 'أغنية المهن للأطفال | ماذا تريد أن تكون؟ تعلّم مع زكريا'),
            _yt('8O40AjQKO5M', 'يا أمي  | أنشودة مؤثرة عن حب الأم ❤️ | تعلم مع زكريا'),
            _yt('VWBjBTWF1gg', 'أنشودة البعوضة لدغت | أنشودة مضحكة للأطفال عن البعوض - تعلم  مع زكريا'),
            _yt('SRpk6S180NA', 'أنشودة الذئب الراعي والخرفان | أناشيد ممتعة للأطفال - تعلم  مع زكريا'),
            _yt('5DoA647sOtY', 'أنشودة أصوات الحيوانات - أغنية القط زيكو 🐱 |  تعلم  مع زكريا'),
          ],
        ),
        _channel(
          id: 'kiki_nadoush',
          title: 'Kiki wa Nadoush',
          order: 20,
          color: 0xFFEF5350,
          sourceType: SourceType.youtubeVideoList,
          videos: [
            _yt('EI3yLs6A-Qk', 'Learn Arabic Colors — Kiki wa Nadoush'),
            _yt('2j8ScIsrYxg', 'Basic Phrases & Counting — Kiki wa Nadoush'),
            _yt('e80_mbmSbC0', 'Colors Short Story — Kiki wa Nadoush'),
            _yt('kixmeJmkzZw', 'Kids Learn the Arabic Alphabet - Alif, Baa, Taa, Thaa'),
            _yt('7BJTXzOngvM', 'Arabic Phrases & Seasons through Culture for Littles-الكلمات و الجمل الأساسية للطفل و ا…'),
            _yt('kvpBcXpGFkE', 'Goodnight Farm Toddler + Baby Bedtime Story in Arabic-تصبحوا على خير يا مزرعة'),
            _yt('7Sq7yRGx_Iw', 'حلوى ملونة حلوى ملونة أين أنت؟ | اغاني اطفال | كيكي وميوميو | بيبي باص | BabyBus Arabic'),
            _yt('xk0MruB1_xU', 'أغنية المهن | اغاني اطفال | كيكي وميوميو | بيبي باص | BabyBus Arabic'),
            _yt('vPiLiiwlSIs', 'الديناصورات على قيد الحياة | ديناصورات اطفال | اغاني اطفال | كيكي وميوميو | بيبي باص |…'),
            _yt('WcnX80xP1_w', 'الوحش استحتم مع كيكي | اغاني الاستحمام | كيكي وميوميو | اغاني اطفال | بيبي باص | BabyBu…'),
            _yt('DnpV37ukXaI', 'كيكي وميوميو انقاذ حيوانات البحر🐬 | اغاني اطفال | حيوانات للاطفال | بيبي باص🦈 | BabyBus…'),
            _yt('sITnyYWpezE', 'كيكي يعد فشار لذيذ | كيكي وميوميو | اغاني اطفال | بيبي باص | BabyBus Arabic'),
            _yt('R7ucLUYdAzU', 'كيكي و شاحنة بناء | اغاني اطفال | كيكي وميوميو | بيبي باص | BabyBus Arabic'),
            _yt('VM7P3Zxaymo', 'أغنية الغميضة | اغاني اطفال | كيكي وميوميو | بيبي باص | BabyBus Arabic'),
            _yt('0jEn8P4d8es', 'أين الربيع؟ | اغاني اطفال | كيكي وميوميو | بيبي باص | BabyBus Arabic'),
          ],
        ),
        _channel(
          id: 'rayan',
          title: 'Rayan',
          order: 21,
          color: 0xFFAB47BC,
          sourceType: SourceType.youtubeVideoList,
          videos: [
            _yt('yPhFBBMWbPU', 'Shapes & Directions in Arabic — Rayan'),
            _yt('hMXsohVaPGQ', 'خضار وفواكه وألوان وأرقام — ريان'),
            _yt('csUnMp9Gdjo', 'الأرقام بالعربية — ريان'),
            _yt('pfzBh3okwe0', 'أشكال وألوان وأحجام — ريان'),
            _yt('ojfQ6yB_Liw', 'كلمات وألوان وفواكه — ريان'),
            _yt('HVmBoF4rMoU', 'نغمة بسم ريان ريان'),
            _yt('Qc9OvGX6v48', 'برافو عليك 🕺🏻'),
            _yt('-B1dB3eaXP0', 'تعليم الاطفال باللغة العربية الفصحى Learning Arabic for Kids & Babies'),
            _yt('YUcWEupG10E', 'ربى مهند مشهورة التيك توك تبكي بسبب شخص مجهول يبخ عليها ويُصيب عينها اثناء احتفالات يوم…'),
            _yt('eyalR-w_jpw', 'شباب البومب شفي ولدك 🤣😭'),
            _yt('Fox5r0MitPc', 'تركي في فلم هوليود #العراق #مصر #اكسبلور_explore #السعودية_الرياض_الكويت_قطر_عمان_الارد…'),
            _yt('4s1hCzZ90rs', 'سحاب مصدومه من دخول العريس 🥺😂 ملكه يوشا وموسى ♥️💍'),
            _yt('OMCeZ-HLNMw', 'مستقبل ريان'),
            _yt('BQYFOsx7yBc', 'رقص طفل على شيله اسمع اسمع يام وقحطان 😍رقص أطفال 💫💥💥'),
            _yt('bjj_5BP6Sag', 'رقص لين السريحي ولين عبد العزيز'),
            _yt('YJAzeybFlVk', 'بنت الديره ابهرتهم في التايكوندو'),
            _yt('oF_Vg_xH-7U', 'زعلت لأن أختها مريضة وهي لا 😂 | الين وتالين'),
          ],
        ),
        _channel(
          id: 'sweet_kalima',
          title: 'Sweet Kalima',
          order: 22,
          color: 0xFFFFCA28,
          sourceType: SourceType.youtubeVideoList,
          videos: [
            _yt('En3OJwCqHx8', 'Shapes, Colors & Numbers — Sweet Kalima'),
            _yt('L3MaRZCKq20', 'أغاني تعليمية — الجزء 2 | Sweet Kalima'),
            _yt('U2mZgNj-Ya0', 'أغاني تعليمية للأطفال | Sweet Kalima'),
            _yt('sSAby5cLSbo', 'الروتين الصباحي — Sweet Kalima'),
            _yt('R0asqLFXxzo', 'الفصول الأربعة — Sweet Kalima'),
            _yt('8rbhv2iEohM', 'أغاني الفواكه — Sweet Kalima'),
            _yt('9v-mXV2r6hA', 'Ramadan Songs for Kids | أناشيد رمضان للأطفال | Sweet Kalima'),
            _yt('C-KpyyO8QUI', 'كلمة حلوة | آداب الحديث والحوار للاطفال - بساطة وبطاطا'),
            _yt('7KjeCzFuUGI', 'طيري طيري يا عصفورة 🕊️  ليلا تي في'),
            _yt('d6-iftd7CDA', 'أغنية الكلمة الحلوة | Nice words Song | Lali Kids'),
            _yt('FzG4uDgje3M', 'El Chombo, Dancing Green Alien - Dame Tu Cosita feat. Cutty Ranks (Official Video)'),
            _yt('s3WdZKl_hRg', 'مستشفى الناس للأطفال | أغنية "وده مين" بصوت أطفال  مستشفى الناس'),
            _yt('qkaT1jv6FZA', 'أغنية توت توت | اغاني اطفال | قناة ليا تشاتشا | LiaChaCha'),
            _yt('l90IBX0wqOE', 'مجموعة من اجمل اغاني الاطفال  | قناة أسرتنا'),
            _yt('aNpYAjqgjJs', 'أنشودة الحواس الخمس -  أنا إنسان لي إحساس'),
            _yt('S5x1xVo-5EU', 'If You\'re Happy arabic (Learn arabic) - Chanson pour apprendre l\'arabe أغاني أطفال : إذ…'),
            _yt('4170WyPU4yI', 'أغنية وين عينك ومجموعة أغاني للاطفال  | قناة مرح كي جي - Marah KG'),
            _yt('FWujY0xauDM', 'Platinum Records - بنيتي الحبوبة'),
          ],
        ),
        _channel(
          id: 'abata',
          title: 'Abata',
          order: 23,
          color: 0xFF8D6E63,
          sourceType: SourceType.youtubeVideoList,
          videos: [
            _yt('sVtaIloYxvw', 'Arabic Alphabet with Chalk — Abata'),
            _yt('AekHJ4m4dks', 'Sea Arabic Alphabet Song — Abata'),
            _yt('xkvkf4LhQKU', 'Dancing Arabic Alphabet Song — Abata'),
            _yt('cSQQ2JATO5I', 'Hijaiyah Puzzle — Abata'),
            _yt('6JnixgqoLbQ', 'Learn ALIF Letters — Abata'),
            _yt('TF8O-XDwX0o', 'Animation 3D Juz Amma Al-Fatihah | Recite Quran with Battar Train Hijaiyah | ABATA Channel'),
            _yt('M2ekL2JHju4', 'Murottal Juz Amma Al Fatihah Animation 3D Learning Letters Arabic Alphabet | Abata'),
            _yt('0ueMNpj44Ts', 'Arabic Alphabet Caterpillar Train Toy Baby for Children and Kids | Abata'),
            _yt('KCc9c8X5xW4', 'SHALLAWAT BADAR Video Animation Arabic Learning For Children and Kids | Abata Song'),
            _yt('I7VGdoHa4XY', 'Learn Surah Al-Fatiha | Quran for Kids | Search and Find Cartoon | Abata'),
            _yt('Km6bpUhlgwg', 'Murottal Juz Amma Al Quraisy Animation 3D Learning Letters Arabic Alphabet | Abata'),
            _yt('F8C41Qntc48', 'Murottal Juz Amma Al Ikhlas Animation 3D Learning Letters Arabic Alphabet | Abata'),
            _yt('qP4SEYmjBNU', 'Hammer Fun Game Learn Arabic Alphabetic For Children and Kids | Abata'),
            _yt('uMqlklXHudY', 'Playground Song Learn letters Arabic Alphabet with Battar Train Hijaiyah For Kids | Abata'),
            _yt('4FlSFj_pT2k', 'Murottal Juz Amma An Naas Animation 3D Learning Letters Arabic Alphabet | Abata'),
            _yt('4VOg_IhKLbc', 'Murottal Juz Amma Al Falaq Animation 3D Learning Letters Arabic Alphabet by Abata'),
            _yt('2UDYA7uhx-Y', 'Animation 3D Juz Amma Al - Falaq | Recite Quran with Battar Train Hijaiyah | ABATA Channel'),
          ],
        ),
        _channel(
          id: 'sara_duck',
          title: 'Sarah & Duck',
          order: 24,
          color: 0xFF26C6DA,
          playlist: _uploadsOf('UC3OUMU3s7Oy6Ta0wnpZFBWw'),
          videos: [
            _yt('EOj_7ZYmCOI', 'Cheer Up Donkey — Sarah & Duck'),
            _yt('e69BdjwjDxk', 'Bouncy Ball — Sarah & Duck'),
            _yt('zGn6PwRkD7c', 'Sarah, Duck and the Penguins'),
            _yt('tavYEmefXgI', '1 Hour Marathon — Sarah & Duck'),
            _yt('F87fpmUgPUA', '30 mins Full Episodes — Sarah & Duck'),
            _yt('wWxzi_obAUw', 'Strawberry Souffle — Sarah & Duck'),
            _yt('_zHfVdvx6OA', 'Pipe Conductor — Sarah & Duck'),
            _yt('tusaLnKrFYI', 'Duck Dresses Up As a Robot | Kids Cartoon | Sarah & Duck'),
            _yt('HvYedgrsaiU', 'Tennis Tennis Tennis Song With Sarah & Duck'),
            _yt('A0y_yRBeNhc', 'The Shallots Circus Performance + More Sara & Duck Cartoons for Kids'),
            _yt('bOUBnT1iHJw', 'POV Waiting For The School Bus on The First Day of School #school #backtoschool'),
            _yt('T_3ed7WyiSU', 'Sarah & Duck and The Ball That Won\'t Bounce | Kids Cartoon'),
            _yt('HnfUNJ_AzSk', 'Counting The Grass With Sarah & Duck #kidscartoon #summer #counting'),
            _yt('JmgOY_BiAdo', 'Sarah & Duck Learn to Play Doubles Tennis Outside + More Cartoons for Kids'),
            _yt('ej2J8h1Kvtc', 'The Carousel Song With Sarah & Duck - Instrumental Music for Toddlers'),
            _yt('pCX_Cahya6Y', 'What\'s The Weather Like Today?'),
            _yt('E81F2SM_5sg', 'Sarah and Duck\'s Cake Bake | Cartoon for Kids'),
          ],
        ),
        _channel(
          id: 'twirlywoos',
          title: 'Twirlywoos',
          order: 25,
          color: 0xFFFF7043,
          playlist: _uploadsOf('UC6-m1hdh8xEu-XBJK3v1TPg'),
          videos: [
            _yt('yS4vFgys9-U', 'Soft — Twirlywoos'),
            _yt('lRVTYTWPUhU', 'This way, that way — Twirlywoos'),
            _yt('phqqLsmOxic', 'Joining Up! — Twirlywoos'),
            _yt('Ya45-PIVjhA', 'Sneaking in the Kitchen — Twirlywoos'),
            _yt('wAFiVXz1NNw', 'Full — Twirlywoos'),
            _yt('Wg0JkKmQY6A', 'Connecting — Twirlywoos'),
            _yt('8MUQW96Nsks', 'Turning — Twirlywoos'),
            _yt('iagHmqt-Hio', 'Going Over — Twirlywoos'),
            _yt('7JXSOIOebW4', 'Full (Kid Movies) — Twirlywoos'),
            _yt('9l11Fr24dsk', 'Turning | Twirlywoos - WildBrain | Kid Movies'),
            _yt('bHNOY1IbE54', 'Cleaning | Twirlywoos - WildBrain | Kid Movies'),
            _yt('wkgAgM0LYss', 'Going Over | Twirlywoos - WildBrain | Kid Movies'),
            _yt('_98n9qvGDZs', 'In and Out | Twirlywoos - WildBrain | Kid Movies'),
            _yt('3uIqkEAvEOI', 'Up | Twirlywoos - WildBrain | Kid Movies'),
            _yt('p-Sz4lEHNTQ', 'Pulling | Twirlywoos - WildBrain | Kid Movies'),
            _yt('tYS7qhcKoOc', 'Bigger and Bigger | Twirlywoos - WildBrain | Kid Movies'),
            _yt('NRuon2JB7dg', 'Upside Down | Twirlywoos - WildBrain | Kid Movies'),
            _yt('uXQY6xlZvqI', 'Behind pt. 2| Twirlywoos - WildBrain | Kid Movies'),
            _yt('JX74zYucaiM', 'Longer | Twirlywoos - WildBrain | Kid Movies'),
          ],
        ),
        _channel(
          id: 'barney',
          title: 'Barney & Friends',
          order: 26,
          color: 0xFF7CB342,
          playlist: _uploadsOf('UCelJG1JV-pKYGOG3AM17Wvg'),
          videos: [
            _yt('HoS5Dv4kAx8', 'I Love You — Barney Nursery Rhymes'),
            _yt('eb7yLV9moeU', 'Learning Colors with Barney!'),
            _yt('iuxvKiCkVUo', "Barney's Best Animal Songs!"),
            _yt('ecj5DwqT2xE', 'Having a Healthy Snack! — Barney'),
            _yt('Zi5CQbSajXE', 'Learning Something New with Barney!'),
            _yt('gzw6-AbAbK4', "Let's Play Together! — Barney"),
            _yt('dIQCqktBrXc', 'A Friend Like You! — Barney'),
            _yt('OUsNcAxAq8M', 'Full Episodes — Love — Barney'),
            _yt('PDlcqXoOIFI', 'Good Manners & Best Behavior — Barney'),
            _yt('-NpnkSB90-E', 'Up, Down, and Around! — Barney'),
            _yt('4FwrbFxYOOQ', 'My Family and Me — Barney'),
            _yt('pf93hIE1xBU', 'Splish! Splash! — Barney'),
            _yt('qNGGHbtBQWw', 'Team Work! | The More We Work Together | Barney Nursery Rhymes & Kids Songs'),
            _yt('brnTSuWj9Ms', 'Best of Nursey Ryhmes with Barney! | Barney Nursery Rhymes & Kids Songs'),
            _yt('JRufFJw19Ls', 'Doctor, I Have a Boo Boo! | Sing-Along | Barney Nursery Rhymes & Kids Songs'),
            _yt('LeFfX7ysL2A', 'Fire Truck Parade! | Sing-Along | Barney Nursery Rhymes & Kids Songs'),
            _yt('bMyj7Op5dgw', 'Best Animal Songs! 🐾 | Itsy Bitsy Spider & More | Barney Nursery Rhymes & Kids Songs'),
            _yt('UjBj6W5P3EQ', 'It\'s Sunny Outside! | Summer Songs | Barney Nursery Rhymes & Kids Songs'),
            _yt('0Sqgb1bd4jg', 'The Idea Song + More! | Sing-Along | Barney Nursery Rhymes & Kids Songs'),
            _yt('wbmlILHK0qg', 'Barney\'s Big Party! | Sing-Along | Barney Nursery Rhymes & Kids Songs'),
            _yt('bEKsJcFw9Ls', 'Roll, Roll, Roll the Ball | Nursery Rhyme Sing Along with Barney and Friends'),
            _yt('W79vAqM3EQY', 'Uh Oh Yikes Whoopsie | Barney Nursery Rhymes and Kids Songs'),
          ],
        ),
        _channel(
          id: 'dora',
          title: 'Dora the Explorer',
          order: 27,
          color: 0xFFFF7043,
          playlist: _uploadsOf('UCkvPyGW-gsYucCK37UR0q2g'),
          videos: [
            _yt('7bqSFXuEUgo', 'NEW Dora Theme Song! — Dora & Friends'),
            _yt('gFTaVxUynsQ', 'You Can Do It! — Dora & Friends'),
            _yt('kKCLBnKT4dU', 'Best Friends Forever Day — Dora & Friends'),
            _yt('aIkGW0o5NeM', 'Dora Plays with Giant Kitty Cats!'),
            _yt('fAYtT9_iOfI', 'Sunny Flower Scenes with Boots — Dora & Friends'),
            _yt('9e105zgnShg', 'Dora Learns in Nature! 🦎 90 Minutes of Scenes, Songs and More! | Dora & Friends'),
            _yt('LMpA4qTV53o', 'Boots Show and Share with bananas! 🍌 #dora'),
            _yt('uWCtYdb2-cs', 'Cutest Baby Animal Rescues! #2 🦊 Dora\'s Rainforest Rescues for 60 Minutes | Dora & Friends'),
            _yt('a6zeqNL9n3Y', 'Dora flies in a kite festival! 🪁 #dora'),
            _yt('uyu3AIzJ1TA', 'Dora\'s Sunny Flower Scenes with Isa! 🌼 60 Minutes | Dora & Friends | Dora & Friends'),
            _yt('XLR0TLSORcs', 'Dora the Explorer Celebrations, Gifts, and Toys! 🎁 120 Minutes | Dora & Friends'),
            _yt('TZWGyaX0f8o', 'Dora\'s Best Beach & Ocean Moments! w/ Marisol the Mermaid #2 🏖 60 Minutes | Dora & Friends'),
            _yt('TKTtKmhCPRs', 'Dora is mermazing! 🧜‍♀️ #mermaids'),
            _yt('6u9SIrtwsRw', 'Dora & Boots Summer Camp Dance Party! 👯 30 Minutes | Dora & Friends'),
            _yt('aqA1_KWyGkY', 'Dora Speed Races to the Finish Line! 🏁 | Dora & Friends'),
            _yt('9KU-baxQaEk', 'Join Dora the Explorer On a Magical Treasure Hunt for 90 Minutes! 🏴‍☠️ #6 | Dora & Friends'),
            _yt('cECDotWI1Uk', 'Dora Clean Up Time for 30 Minutes! 🧼 Healthy Habits for Kids | Dora & Friends'),
          ],
        ),
        _channel(
          id: 'peppa',
          title: 'Peppa Pig',
          order: 28,
          color: 0xFFEF5350,
          playlist: _uploadsOf('UCAOtE1V7Ots4DjM8JLlrYgg'),
          videos: [
            _yt("XAK5n8XUmfM", "What is Peppa's Favourite Sound? — Full Episodes"),
            _yt('t7dTdE8Aqtw', 'Jumping in Muddy Puddles — Peppa Pig My First Album'),
            _yt('P5vlEeqdJN8', 'Peppa and George Love Jumping in Muddy Puddles!'),
            _yt('jbdck_y74ls', 'Peppa Pig Rides the TRAIN! — LEGO DUPLO'),
            _yt('RafDio654Ws', "Peppa Pig's New Tree House"),
            _yt('blQxZ73C_Vg', 'Tea Party in Her Tree House — Peppa Pig'),
            _yt('e1WO60yYBtg', "Peppa's Magical Treehouse Adventure"),
            _yt('xu1mfnnle0Q', "Peppa Pig's New Tree House (Official)"),
            _yt('y3DHF3wsHZs', 'Peppa Pig 2026 NEWEST Episodes 🐷 Best of Season 10 & 11! 🤩 Summer Adventures 🗺️ | Full…'),
            _yt('E660YrTDYrk', 'Grandpa Pig Gets an X-RAY! 🩻 Hospital SLEEPOVER!  💤 🏥 Peppa Pig Full Episodes | 1 Hour'),
          
            _yt('WOkE3j6p35Y', 'Peppa Pig and the Garbage Truck'),
            _yt('Iyl6jZJV4M0', 'George and Peppa\'s HEARING Test! 🎧 Doctor Visit 🏥 Peppa Pig Full Episodes | 1 Hour'),
            _yt('MQMlxwYLbw4', 'Peppa Learns How to HOLD a BABY! 🍼  Peppa Pig Full Episodes | 1 Hour'),
            _yt('yXsO04168uQ', 'Peppa Pig Full Episodes |Stuck in Traffic with Peppa #91'),
            _yt('lwTYuNjsZlE', 'Peppa Pig Playground ☎️ | Olden Days | Peppa Pig Full Episodes'),
            _yt('I6GtYvmA4rc', 'Peppa Pig Full Episodes |Long Train Journey #49'),
            _yt('klyRtMINds4', 'Best of Peppa Pig - ♥ Best of Peppa Pig Episodes and Activities #44♥'),
            _yt('n_JHSNdY2sw', 'Peppa Pig Full Episodes |Captain Daddy Dog #113'),
          ],
        ),
        _channel(
          id: 'ben_and_holly',
          title: "Ben & Holly",
          order: 29,
          color: 0xFF66BB6A,
          playlist: _uploadsOf('UC2UhuvjTIrR0Ck2KrkvRcuA'),
          videos: [
            _yt('mLHPMMKTNRI', 'The Royal Fairy Picnic — Ben & Holly'),
            _yt('edAhVTPprT0', 'The Toy Robot — Ben & Holly'),
            _yt('37Cz9nqz5fg', "King Thistle's Busiest Day — Ben & Holly"),
            _yt('gHga2hc_NsE', 'The Elf Farm — Ben & Holly'),
            _yt('dR0UCe5DXjk', 'Gaston Moves Into the Castle — Ben & Holly'),
            _yt('3w1Z_YhB008', 'Holly Goes to Elf School — Ben & Holly'),
            _yt('3QCsaMMt3I4', 'Gaston Goes To School — Ben & Holly'),
            _yt('it_Z9yZ77fM', 'Ben Turned Into a Frog — Ben & Holly'),
            _yt('AWD6XYd8iOA', "Holly Forgets Ben's Birthday — Ben & Holly"),
            _yt('AWWywfv69ww', 'The Elf Band Saves the Day — Ben & Holly'),
            _yt('rZ5kKVQkqM4', 'Ben Learns to Tell Time — Ben & Holly'),
            _yt('WOddu_AdGPU', 'What are Ben and Holly Cooking? — Ben & Holly'),
            _yt('hCblA3qIFGs', 'Learn to Share — Ben & Holly'),
            _yt('t5x7QurObts', 'Holly Needs Help — Ben & Holly'),
            _yt('GvGFWEJq2oE', 'King Thistle Has a Cold — Ben & Holly'),
            _yt('g-bNPrZWmXg', "King Thistle's Clothes Shrink — Ben & Holly"),
            _yt('iMDZv-7pRrM', 'The Mystery of the Lost Egg — Ben & Holly'),
            _yt('4Jr6Nfngto0', "Nanny Plum's Windmill — Ben & Holly"),
            _yt('GzxW_whnX3I', "Betty's Butterfly Surprise — Ben & Holly"),
            _yt('ghv0qtbeyeY', "Holly's Sandcastle Surprise — Ben & Holly"),
            _yt('4vtNAhsBv2U', '🚀 Granny & Grandpa’s WILDEST Magic Party! ✨🏰 | Ben & Holly | Cartoons for Kids'),
            _yt('rSnyLUfALNU', '🚨 Gaston Goes to the Vet & Elf Rescue Saves the Day! 🐞| Ben and Holly’s | Cartoons for…'),
            _yt('JW5i6sPqniM', '🐜 The Ants STEAL Everything 😂 | Ben & Holly | Cartoons for Kids'),
            _yt('vZI5YVyj71Q', '👑 Queen Holly\'s Ice Cream Disaster! 😂 | Ben and Holly’s Little Kingdom | Cartoons for Kids'),
            _yt('mX3AAq4fLpo', 'Ben and Holly\'s Little Kingdom ✨ Spaceship Food and Drink Maker! 🥤 Cartoons For Kids'),
            _yt('LevDq_11MKk', 'Ben and Holly\'s Little Kingdom | Nanny Plum\'s Giant Pudding! - Full Episode | Kids Cart…'),
            _yt('W2BL8KauvqY', 'Ben and Holly\'s Little Kingdom | Triple Episode: The Best Meal EVER!!! | Cartoons For Kids'),
            _yt('-yj335Pq75c', 'Lucy\'s Picnic | Ben and Holly\'s Little Kingdom | Cartoons For Kids'),
            _yt('0umQOYtl_M0', 'Ben and Holly’s Little Kingdom | Morning Magic | Cartoon for Kids'),
            _yt('B-shOepR8JI', 'Ben and Holly’s Little Kingdom | King Thistle Loses His Chill | Kids Videos'),
          ],
        ),
        _channel(
          id: 'lego_duplo',
          title: 'LEGO DUPLO',
          order: 30,
          color: 0xFFFDD835,
          sourceType: SourceType.youtubeVideoList,
          videos: [
            _yt('fwg0UIw0Efs', 'LEGO DUPLO Numbers & Colors in Arabic'),
            _yt('w7aZLVaLTlM', 'LEGO DUPLO Vehicles & Colors'),
            _yt('01JxHFDBdzE', 'LEGO DUPLO Creative Animals Unbox'),
            _yt('a0uPqr_iASU', 'LEGO DUPLO Animal Build'),
            _yt('jvCdmPsAn40', 'LEGO DUPLO Balancing Tree'),
            _yt('xvxQeQfdifk', 'LEGO DUPLO Marble Run'),
            _yt('fh6XF6u4EVs', 'LEGO DUPLO - Hometown Heroes Songs | Learning For Toddlers | Nursery Rhymes | Cartoon a…'),
            _yt('yQwP7kiNipg', 'Fireman Saves the Day! 🚒| Trucks & Construction Vehicles for Kids | LEGO DUPLO | Cartoo…'),
            _yt('4BuSLGFVSaA', 'LEGO DUPLO - Windy Day | Story Time | Cartoons for Kids | Toddlers Learning'),
            _yt('ENpxAYLT7tk', 'LEGO DUPLO - Pip, Pip Hooray! Birthday Celebration | Story Time | Kids Cartoons | Toddl…'),
            _yt('lS-Vb0Vr-4Q', 'LEGO DUPLO | Winter Wonderland Adventure + More Fun Stories | Cartoon for Kids | Presch…'),
            _yt('j5hn5OzF7vI', 'Humpty Dumpty + More Nursery Rhymes | 1 HOUR OF LEGO DUPLO | Kids Songs | Cartoon for Kids'),
            _yt('jAzbTGmdbn4', 'LEGO DUPLO - Animal Adventure | Story Time | Cartoons for Kids | Toddlers Learning | Ma…'),
            _yt('MY4qzFgzVf8', 'LEGO DUPLO Disney Mickey & Minnie\'s Birthday Party! 🎈| LEGO Little Ones'),
            _yt('gGm5LVOLIbU', 'Let’s Build a Home Together 🏡💛 Preschool Learning & Kids Cartoon | LEGO DUPLO | LEGO Li…'),
            _yt('YdEHRXDrf0Q', 'Number Train + More Nursery Rhymes | 1 HOUR OF LEGO DUPLO | Kids Songs | Cartoon for Kids'),
            _yt('65T4zjOfBhc', 'Season 1 Episodes | Nursery Rhymes | Learning For Toddlers | LEGO DUPLO'),
            _yt('0jOLWSuqMFI', 'It\'s a Jungle Animal Safari!🦒🐼🐘| Learn About Animals | LEGO DUPLO | Kids Songs | Cartoo…'),
          ],
        ),
        _channel(
          id: 'play_doh',
          title: 'Play-Doh',
          order: 31,
          color: 0xFFFF8A65,
          sourceType: SourceType.youtubeVideoList,
          videos: [
            _yt('2FyKZKNls4c', 'Play-Doh Cookie Man & Shapes'),
            _yt('8581xy-tGqw', 'Play-Doh Rainbow Ice Cream'),
            _yt('kS9fxiOdiGs', 'Marble Run Plasticine Race'),
            _yt('F4ICHmkVGtQ', 'Magic Marble Run Compilation'),
            _yt('Ks1Q-GZvaxI', 'Play-Doh | The Bald and the Beautiful | Full EPISODE | Funny Cartoons For Kids'),
            _yt('W82Qf2qZm3A', 'Dentist Adventure 🦷 Practice Brushing Teeth and Hygiene with Play-Doh Videos ⭐️ The Pla…'),
            _yt('HkpOL_iAHng', 'Play Doh Videos | Pizza Topping Challenge 🍕 Stop Motion | The Play-Doh Show'),
            _yt('Juj6Rr8f_O4', 'Play Doh Videos | Popcorn Party 🍿 Explosion | Stop Motion | The Play-Doh Show'),
            _yt('TXz3VUW8ags', 'Pizza Making Robot! 🍕 The Play-Doh Show'),
            _yt('RK9Ex9lBDiI', 'Play-Doh Pizza Topping Challenge 🍕 Kids Animation | The Play-Doh Show ⭐️'),
            _yt('pfScG1y0VlM', 'Play-Doh Official 🌋 Play-Doh Volcano Erupts! 🌋 Funny Colors'),
            _yt('r6mJ27oY9oI', 'Candy Factory Fun 🍬  Kids Animation | The Play-Doh Show ⭐️'),
            _yt('kDvyE3T39Z0', 'Play Doh Lion #diy #playdoh #kidschannel #education #forkids #preschool #trending #lear…'),
            _yt('bGMJQa6tJMA', 'The Floor is Lava 🔥 That\'s Not Stopping Orange | Play-Doh Videos'),
            _yt('5MZrm3cH2jA', 'When the students were uninspired, our Play-Doh Professor was there to help 🦄🐞 #KidsCan'),
            _yt('jPEIczwzmc0', 'Dentist Adventure 🦷 Tooth Trouble | Play-Doh Videos'),
          ],
        ),
        _channel(
          id: 'toy_kitchen',
          title: 'Toy Kitchen',
          order: 32,
          color: 0xFF90A4AE,
          sourceType: SourceType.youtubeVideoList,
          videos: [
            _yt('mSUJM2naI7I', 'Travel Kitchen Playset Unboxing'),
            _yt('TL3e2UZQxPE', 'Kitchen Set & Toy Fruits'),
            _yt('Yq-OPFIYOAk', 'Wendy Pretend Play Cooking Food w/ Peppa Pig Restaurant Kitchen Oven & Refrigerator Toys'),
            _yt('NFUivBelIAA', 'Wendy Pretend Play w/ Hello Kitty Kitchen &Tea Party Kids Food Toys'),
            _yt('dTecJGL62uM', 'Wendy & Emma Pretend Play w/ Giant Kitchen Cooking Toy Compilation'),
            _yt('Gp0rkS4O8WU', 'Satisfying Unboxing & Review of Miniature — Making Cooking Rice in My Toy Kitchen Set! 🍟'),
            _yt('xq5f3SMU7lA', 'Baby doll kitchen cart food cooking toys baby Doli play'),
            _yt('q-FJ_h-Nn8c', 'New Playhouse and Pretend Play Cooking Food on Kitchen Toy'),
            _yt('JPDnzPb2AUY', 'Jannie Pretend Play with DELUXE Kitchen Toy Set'),
            _yt('JsFa8d2_iCc', 'Food Truck Play Kitchen - Cooking and Serving Hot Dogs, Burgers, Pizza, and Pretend Foods'),
            _yt('fbatqm3-5nU', 'Roma and Diana Pretend Play Cooking Food Toys with Kitchen Play Set'),
            _yt('hqzbdR0FaUw', 'Lets Create a Birthday Dinner Party in our Toy Kitchen'),
            _yt('aq2TEynHNDU', 'Best Toy Food Videos for Kids - Let\'s Have Fun in the Kitchen!'),
            _yt('IoZoSlkrhGE', 'Alice Pretend Princess & playing in Restaurant with Kitchen Toys'),
          ],
        ),
        _channel(
          id: 'dancing_fruit',
          title: 'Dancing Fruit',
          order: 33,
          color: 0xFFEC407A,
          sourceType: SourceType.youtubeVideoList,
          videos: [
            _yt('7mR81x2Fk7g', 'Dancing Fruit! — 1 Hour Mix — Hey Bear Sensory'),
            _yt('ALaQvK7KZOY', 'Dance, Colors and Counting — Dancing Fruit & Funky Veggies'),
            _yt('kAxdvigZtw8', 'Best of Dancing Fruit and Funky Veggies — Dance Party'),
            _yt('b65MoVwANq4', 'Disco Fruit Party — Dancing Fruit with Cumbia'),
            _yt('KPP4Cfupzhs', 'Smoothie Mix — Fun Dance Video'),
            _yt('xOUdk2LdXrs', "Let's Dance! — Avocadosaurus and Party Strawberries"),
            _yt('4i2dQ_Zp29w', 'My Happy Song 🍓 | Baby Fruit Dancing | High Contrast Sensory Video for Toddlers'),
            _yt('atbA1IQmP2Y', 'Baby Fruit Dancing - 20 MIN - WELCOME SPRING! 🌼🌼 Sensory Video 🌈💐🌹🌷'),
            _yt('Yjf9JU1iVSo', 'Rain Rain Go Away ☂️🍎 | Dancing Fruit Baby Sensory Video Visual Stimulation Animation'),
            _yt('5nHfUcaIuak', 'BINGO 🐶 🍎 | Dancing Fruit Baby Sensory Video Visual Stimulation Animation'),
            _yt('6eVCh8Itmx8', 'Jump, Dodge & Collect VitaSparks - Juani’s Big Indoor Playground Adventure! |  Baby Fru…'),
            _yt('nSHKvAMFj_8', 'CHICKEN BANANA SONG🍌🐔 Baby Fruit Dancing | Low Stimulation Sensory Video for Babies'),
            _yt('N7VzZdsvaAY', 'ABC Train 🚂🔤🍎 Alphabet ABC Song | Dancing Fruit Baby Sensory Video Visual Stimulation'),
            _yt('qRZ1URXOKLg', 'Wheels on the Bus 🚌 🍎 | Dancing Fruit Baby Sensory Video Visual Stimulation Animation'),
            _yt('Iq5qXtKQBCU', 'Dancing Fruits for Baby Sleep | Sleep Sensory Video'),
            _yt('jIA1CGc6zeU', '🚌🍉 Funky Fruits Baby Sensory | Watermelon Wheels On The Bus – Fun Animation and Upbeat…'),
            _yt('2fZusVOjEpQ', 'Cute Fruit Babies Dance Party | Oddly Satisfying AI'),
            _yt('wzGRs-C8kqs', 'Hey Bear Sensory - Fruit Salad Dance Party - Counting 1 to 10 - Fun animation with music'),
          ],
        ),
        _channel(
          id: 'toyor_baby',
          title: 'طيور بيبي',
          order: 34,
          color: 0xFF81C784,
          sourceType: SourceType.youtubeVideoList,
          videos: [
            _yt('_tN--Xk4kaE', 'دعاء النوم — سند مقداد | طيور بيبي'),
            _yt('9hmZtWndznM', 'دعاء قبل الطعام وبعده — سند مقداد | طيور بيبي'),
            _yt('UA6sLNgWRtI', 'شمّام (بدون ايقاع) — طيور بيبي'),
            _yt('42oNUPf_SsM', 'دعسوقة (بدون إيقاع) — طيور بيبي'),
            _yt('OHM8yH2QRC8', 'شاكر والببغاء الشاطر — العشرة المبشرون بالجنة'),
            _yt('-l5_ao_oxmg', 'شاكر والببغاء الشاطر — الصلوات'),
            _yt('iSuhEcI1HOQ', 'شاكر والببغاء الشاطر — المدينة المنورة'),
            _yt('QhAc8NS8J_M', 'شمّام — طيور بيبي'),
            _yt('x6s8KLzbq28', 'الديك بيصحى (بدون إيقاع) — طيور بيبي'),
            _yt('3pI5IhE1sSE', 'حمار جحا (بدون إيقاع) — طيور بيبي'),
            _yt('ZgUCuW8aRCY', 'الليمونة والبرتقالة (بدون إيقاع) — طيور بيبي'),
            _yt('j4ViMQxKY4A', 'الأرنب والثعلب (بدون إيقاع) — طيور بيبي'),
            _yt('EmSa43Juh64', 'ساعة من أغاني طيور بيبي - توزيع جديد'),
            _yt('cFjhQK0DVQc', 'أم جميل والشهر الفضيل (توزيع جديد) - طيور بيبي Toyor Baby'),
            _yt('lXke0OODwNQ', 'نهاية ثعلب (توزيع جديد) - طيور بيبي Toyor Baby'),
            _yt('A6_Iq-JmkI0', 'حميدو - طيور بيبي | Toyor Baby'),
            _yt('ZnSx-k1yk9M', 'البندورة الحمرا - طيور بيبي | Toyor Baby'),
            _yt('XyMBV6vaUZo', 'جننتوني - جنى مقداد | طيور الجنة'),
            _yt('UkQWkE7c0Yc', 'الراعي الكذاب - طيور بيبي Toyor Baby'),
            _yt('DkiPeMjORa4', '3 عصافير -  طيور بيبي Toyor Baby'),
            _yt('WwLHY2lv__Q', 'الليمونة والبرتقالة - طيور بيبي Toyor Baby'),
            _yt('B0BC-5Z6BFo', 'ليلى والذئب - طيور بيبي Toyor Baby'),
          ],
        ),
        _channel(
          id: 'pingu',
          title: 'Pingu',
          order: 35,
          color: 0xFF42A5F5,
          playlist: _uploadsOf('UCM88mtSE0zRTn5ae4EbYcuw'),
          videos: [
            _yt('fWb-pNyPzdo', 'The Flying Pingu! — Official Channel'),
            _yt('e3egZ7tLXV4', 'A Helping Pingu! — Official Channel'),
            _yt('67zm4V1F0Z0', 'Painting Pingu! — Official Channel'),
            _yt('cXmY4mlM6OI', 'Like Father Like Pingu! — Official Channel'),
            _yt('PpwYRAWTD8c', 'Pingu the Doctor — Official Channel'),
            _yt('m3KuDiBEtgU', 'Pingu and the Broken Vase — Official Channel'),
            _yt('Y1rkjGfX4Z4', 'Flying a Kite! 🐧 #Pingu'),
            _yt('NZkhSWJAo0o', 'Story Time! 🐧 #Pingu'),
            _yt('91jNHnMEGsI', 'Endless Laughter! 🐧 #Pingu'),
            _yt('wVcTqW-UZGY', 'Pingu Loses 🐧 | Pingu - Official Channel | Cartoons For Kids'),
            _yt('OZ9tCtKvr48', 'Animal Feeding Time! 🐧 #Pingu'),
            _yt('FzN6iJm6bpw', 'The NEW Scooter! 🐧 | Pingu - Official Channel | Cartoons For Kids'),
            _yt('1-uWy9PF1i4', 'What Time is It?! 🐧 #Pingu'),
            _yt('C-98E7aoHZE', 'This is Going to FALL! 🐧 #Pingu'),
            _yt('7Uoug3d3AJE', 'The Mountaineer! 🐧 | Pingu - Official Channel | Cartoons For Kids'),
            _yt('1w42EuvQoBo', 'Icecream Day! 🐧 #Pingu'),
          ],
        ),
        _channel(
          id: 'daniel_tiger',
          title: 'Daniel Tiger',
          order: 36,
          color: 0xFFFFA726,
          playlist: _uploadsOf('UCDqgSnRMGVx3dP4sn3ATZMA'),
          videos: [
            _yt("OrNlkDVk_PA", "Daniel's Big Emotions — Daniel Tiger"),
            _yt('N4cTNBbDTdw', 'Daniel Learns Good Manners — Daniel Tiger'),
            _yt('R6nF76uDWDA', 'Daniel Eats Healthy — Daniel Tiger'),
            _yt('9AfD-N9HK8s', 'Bath Time with Daniel Tiger — Full Episodes'),
            _yt('oloZANav_g8', 'Potty Training! — Daniel Tiger'),
            _yt('IGM-r8baTN4', 'Daniel Learns to Swing — Daniel Tiger'),
            _yt('zvJAcFoFXxE', 'Learning Patience — Daniel Tiger'),
            _yt('mnc6a3aA_yA', "Won't You Be My Neighbour? — Daniel Tiger"),
            _yt('8p8ADCLz3Hk', 'Baby Margaret is My Best Friend — Daniel Tiger'),
            _yt('5tb0ukBVbA0', 'Neighbourhood Jobs — Daniel Tiger'),
            _yt('Srvt0RQhpus', 'Daniel Visits the Doctor! | Daniel Tiger\'s Neighbourhood'),
            _yt('xnlsj5eRfuU', 'Daniel Plays with Different Animals! | Daniel Tiger\'s Neighbourhood'),
            _yt('tJae0hJIh94', 'Daniel Does Arts and Crafts | Daniel Tiger\'s Neighbourhood'),
            _yt('Zqqw0Z9h2pM', 'Daniel Discovers New Food | Daniel Tiger\'s Neighbourhood'),
            _yt('_gcMBwof1JA', 'Daniel Deals with Tough Emotions | Full Episodes | Daniel Tiger\'s Neighbourhood'),
            _yt('ppwG65dGXzc', 'Sharing your Emotions is Important! | Daniel Tiger\'s Neighbourhood'),
            _yt('8EzTNQT43TU', 'Daniel Explores the Life of Ants 🐜 🐜 🐜| Daniel Tiger\'s Neighbourhood'),
            _yt('bg1YQ5mV5bo', 'Daniel Does Arts & Crafts | Daniel Tiger\'s Neighbourhood'),
            _yt('EctpCVLoXlY', 'Daniel\'s Make-Believe Songs 🎶 | Daniel Tiger\'s Neighbourhood'),
          ],
        ),
        _channel(
          id: 'hey_duggee',
          title: 'Hey Duggee',
          order: 37,
          color: 0xFFFFCA28,
          playlist: _uploadsOf('UCj_mFUb-47d9QNiJ5556LjQ'),
          videos: [
            _yt('W4oqUjPj-pI', 'The Drawing Badge — Hey Duggee'),
            _yt('_zJJVO4XXZs', 'The Colour Badge — Hey Duggee'),
            _yt('RhMecZiUEiY', 'The Decorating Badge — Hey Duggee'),
            _yt('VVMjTvc8qbQ', 'The Key Badge — Hey Duggee'),
            _yt('6bxOoxBheb0', 'Feel-Good Happy Days With Duggee'),
            _yt('BBleojshabk', 'The Recipe Badge — Hey Duggee'),
            _yt('J0Jc0MSQglg', 'The Delivery Badge — Hey Duggee'),
            _yt('dIoRncsoFm8', 'The Shopping Badge — Hey Duggee'),
            _yt('l0L9WACaMCc', "Roly's First Day — Hey Duggee"),
            _yt('Kr9LM1WLwaY', '45+ Mins of Kids\' Songs & Nursery Rhymes | The Wheels on the Bus & More! | Hey Duggee O…'),
            _yt('SL6ANbbguXE', 'Baby Squirrel Adventures and MORE! 🐿️ | Hey Duggee'),
            _yt('ytjAUy5r_VA', 'Let\'s Get Arty! 🎨 | Making Marathon | Hey Duggee'),
            _yt('9TpBgOpALFQ', 'Can You Spot STICK and MORE! | Hey Duggee\'s Squirrel Club'),
            _yt('FF90QXoa8n4', 'Bake Delicious Dishes With Duggee 🍰 | Hey Duggee'),
            _yt('C8b2wN_fFFE', 'Toddler Dinosaur Learning with Duggee 🦕 | Hey Duggee'),
            _yt('5ewzE2_K8AE', 'The Squirrels\' Amazing Space Adventure! 🪐 | Hey Duggee'),
            _yt('YCuLYC-cVs0', 'Duggee\'s Ultimate Art Marathon! 🎨 🖼️ | Hey Duggee'),
            _yt('jmeAgCM3VfI', 'Duggee\'s Best Picnic & Outdoor Adventures! 🧺 | Hey Duggee'),
            _yt('xfc-IDn94_Y', 'School Summer Holidays DUGGEE MARATHON! ☀️ | 70+ Mins | Hey Duggee'),
          ],
        ),
        _channel(
          id: 'numberblocks',
          title: 'Numberblocks',
          order: 38,
          color: 0xFFAB47BC,
          playlist: _numberblocksSeason1Playlist,
          followUploads: true,
          videos: [
            _yt('jVeYnCehEFE', 'One — Numberblocks S1 E1'),
            _yt('bz2oWyDjgbc', 'Another One — Numberblocks S1 E2'),
            _yt('aJzaNIpbUZo', 'Two — Numberblocks S1 E3'),
            _yt('6-duQqX5ECs', 'Three — Numberblocks S1 E4'),
            _yt('IqkSbJqplpg', 'One, Two, Three — Numberblocks S1 E5'),
            _yt('yKAttOvgWJc', 'Three Little Pigs — Numberblocks S1 E8'),
            _yt('Ap5kgJ-bpEQ', 'How to Count — Numberblocks S1 E10'),
            _yt('Wafr8h4EsXg', 'Four | Full Episode - S1 E6 | Numberblocks (Level 1 - Red 🔴)'),
            _yt('-U1wQ0gu0Es', 'Five | Full Episode - S1 E7 | Numberblocks (Level 1 - Red 🔴)'),
            _yt('37E3wokWzlU', 'Off We Go | Full Episode - S1 E9 | Numberblocks (Level 1 - Red 🔴)'),
            _yt('M2u_jRHYUh0', 'Stampolines | Full Episode - S1 E11 | Numberblocks (Level 1 - Red 🔴)'),
            _yt('fJ6k7vkV99o', 'The Whole of Me | Full Episode - S1 E12 | Numberblocks (Level 1 - Red 🔴)'),
            _yt('Vyx-oZpnPhY', 'The Terrible Twos | Full Episode - S1 E13 | Numberblocks (Level 1 - Red 🔴)'),
            _yt('Kv_j6gpD5Jo', 'Holes | Full Episode - S1 E14 | Numberblocks (Level 1 - Red 🔴)'),
            _yt('q4RTnmfOSNI', 'Hide and Seek | Full Episode - S1 E15 | Numberblocks (Level 1 - Red 🔴)'),
            _yt('H2FqfAbf1bM', 'Numberblocks Vacation Fun! | Full Episodes - 1 Hour Compilation | 123 - Numbers Cartoon…'),
            _yt('9I2T8zdB4ck', '🎨 Painting by Numbers | Full Episode - S6 E1 ⭐ | Learn to Count | @Numberblocks'),
          ],
        ),
        _channel(
          id: 'pocoyo',
          title: 'Pocoyo',
          order: 39,
          color: 0xFF29B6F6,
          playlist: _uploadsOf('UChT6ex4rsEDXjJKW7wJAb8w'),
          videos: [
            _yt('CwL_mEsASGY', "Pato's Bedtime — Pocoyo"),
            _yt('_-UEJip10hE', "Elly's Market — Pocoyo"),
            _yt('_g_QHiaKuEs', 'Cooking with Elly — Pocoyo'),
            _yt('eDu9RdFhcg4', 'Magician Pocoyo — Pocoyo'),
            _yt('_b2U6PLIc_E', "Giving Loula a Bath — Pocoyo"),
            _yt('jO-AiyofVEI', "Pocoyo's New Toys — Pocoyo"),
            _yt('swVI1aYW8E0', "It's Shopping Day — Pocoyo (89 min)"),
            _yt('tqAf9tFW00Y', 'Super Babies — Pocoyo (94 min)'),
            _yt('WDQl4w-n9IE', 'Playground Time — Pocoyo (99 min)'),
            _yt('YFCWXJdo4N0', 'Learn The Alphabet — Pocoyo'),
            _yt('rpUmsPMprMU', '🗼 The Amazing Tower 🗼 [Ep17] FUNNY VIDEOS and CARTOONS for KIDS of POCOYO in ENGLISH'),
            _yt('LKnUQcPeVv0', '🛁 Elly\'s Bath 🛁 [Ep16] FUNNY VIDEOS and CARTOONS for KIDS of POCOYO in ENGLISH'),
            _yt('XyITSKXAgn0', '🚗 Wheels 🚗  [Ep15] FUNNY VIDEOS and CARTOONS for KIDS of POCOYO in ENGLISH'),
            _yt('alztoOY6c7U', '🎂 Party Time 🎂  [Ep14] FUNNY VIDEOS and CARTOONS for KIDS of POCOYO in ENGLISH'),
            _yt('ZEzNRBssuYE', '🌵 Hide and Seek 🌵 [Ep13] FUNNY VIDEOS and CARTOONS for KIDS of POCOYO in ENGLISH'),
            _yt('PJh4HUaOecI', '🎾 Tennis for Everyone 🎾 [Ep12] FUNNY VIDEOS and CARTOONS for KIDS of POCOYO in ENGLISH'),
            _yt('VcZXeU6EiJQ', '🎮 Play Time 🎮 [Ep11] FUNNY VIDEOS and CARTOONS for KIDS of POCOYO in ENGLISH'),
            _yt('ssRWSzGUumI', '✈️ Travel with Pato ✈️ [Ep10] FUNNY VIDEOS and CARTOONS for KIDS of POCOYO in ENGLISH'),
            _yt('iX3YMTlXrG4', '🚀 Space Mission 🚀 [Ep09] FUNNY VIDEOS and CARTOONS for KIDS of POCOYO in ENGLISH'),
            _yt('1bzY5BXhW3o', '⛺️ We\'re Going Camping ⛺️ [Ep08] FUNNY VIDEOS and CARTOONS for KIDS of POCOYO in ENGLISH'),
          ],
        ),
        _channel(
          id: 'cocomelon',
          title: 'CoComelon',
          order: 40,
          color: 0xFFFFEE58,
          playlist: _uploadsOf('UCbCmjCuTUZos6Inko4u57UQ'),
          videos: [
            _yt('e_04ZrNroTo', 'Wheels on the Bus — CoComelon'),
            _yt('WRVsOCh907o', 'Bath Song — CoComelon'),
            _yt('ZzAm13KsBCc', 'Bath Song + More — CoComelon'),
            _yt('tgFynI0l06U', 'Old MacDonald Had A Farm + More — CoComelon'),
            _yt('hqehvbhky5k', 'On My Way To School — CoComelon'),
            _yt('wfwvrawZDs8', 'Happy Birthday Song — CoComelon'),
            _yt('qXcMNBQnQMM', 'Songs For Kids Compilation — CoComelon'),
            _yt('fdPu-wvl3KE', 'Peek A Boo — CoComelon'),
            _yt('3G8OSUZgPCw', 'Clap Along with JJ and His Siblings | Beach Boom-Clap | CoComelon Nursery Rhymes & Kids…'),
            _yt('udEJJh19v6E', 'CoComelon: The Movie | Official Teaser Trailer'),
            _yt('F_wuTLqVY7k', 'At Home Science Experiments | Floor is Lava Challenge | CoComelon Nursery Rhymes'),
            _yt('vMH1M0px_-s', 'Play with Cats 🐈 | Cece Had a Little Cat | Animals and Pets | CoComelon Nursery Rhymes'),
            _yt('joP2XFA9WGA', 'Lost in the Forest Song ⭐ Fireflies Lullaby | JJ\'s Animal Time - CoComelon Kids Songs'),
            _yt('zOD7MNxXbmE', 'Let\'s do the BELLY BUTTON DANCE! #cocomelon'),
            _yt('NA35NQX59yk', 'Make a Boba Bear Out of Fruit! 🍊🍓🐻 Easy DIY Crafts for Kids #cocomelon'),
            _yt('NzWX-S_ZRH4', 'Peekaboo I See You - Animal Play Pretend | CoComelon Nursery Rhymes and Kids Songs'),
            _yt('2PU1Cw9V0jE', 'APPLES and BANANAS! 🍎🍌 Let\'s Learn with Ms. Appleberry! #cocomelon #kids #videos'),
            _yt('VVrT0wnLcT0', 'Beach Day Sports & Bath Time Ocean Rescue! | Best Summer Songs For Kids | CoComelon Nur…'),
          ],
        ),
        _channel(
          id: 'masha',
          title: 'Masha and the Bear',
          order: 41,
          color: 0xFFEF5350,
          playlist: _uploadsOf('UCu59yAFE8fM0sVNTipR4edw'),
          videos: [
            _yt('qBp1rCz_yQU', 'Recipe For Disaster — Masha and the Bear'),
            _yt('1Kt9RhxJdzk', 'Recipe For Disaster (4K) — Masha and the Bear'),
            _yt('g9CMF85dAt4', 'Laundry Day — Best Episodes Collection'),
            _yt('AV-UBYOGB_o', 'Why Should We Play Games? — Best Episodes'),
            _yt('R6Oh1xUmB3E', 'Honey Day — Cartoon Collection'),
            _yt('erwBhzx3eok', 'أفضل طريقة لقضاء اليوم — ماشا والدب'),
            _yt('EsGkXt6nneE', 'أميرة الأسنان الحلوة — ماشا والدب'),
            _yt('INyR_Dl7rVk', 'طيف ظريف — ماشا والدب'),
            _yt('lKu5rUY5c4s', '👧💭 Masha Reacts to: Big Surprise? 🎁🎉 Best episodes cartoon collection 🎬 Masha and the B…'),
            _yt('E8GP3313Mto', 'Masha and the Bear 2026 🤔 Guess What?❓Best episodes cartoon collection 🎬'),
            _yt('VDd245acOG4', 'Masha and the Bear 🎉 NEW EPISODE 2026 🙈 Mind the Door 👁️🚪 (Episode 144)'),
            _yt('_w7bXOkPZpU', 'Masha and the Bear 2026 🤪🗓️ Fool\'s Day Everyday! 🙈 Mind the Door 👁️🚪Coming on August 7!'),
            _yt('0I_r_fgwZ0Y', 'Masha and the Bear 2026 ⏱️ 🏊‍♂️ Last To Leave The  Water Wins! 🌊🏆 Best episodes cartoon…'),
            _yt('KHs13DY7uLE', 'Masha and the Bear 2026 🤫❓Secret Episode 🥷🌪️ Best episodes cartoon collection 🎬'),
            _yt('0c_os2vaYtI', 'Masha and the Bear 2026 ⛱️❄️ July Snowman?! ☀️⛄️ Best episodes cartoon collection 🎬'),
            _yt('fD-zWUqBfFs', 'Masha and the Bear 2026 🐑🤗 Furry Hug Challenge! 🐾💖 Best episodes cartoon collection 🎬'),
            _yt('JbDxtgcF3F0', 'Masha and the Bear 2026 🎬 NEW EPISODE! 🥰 Berry Naughty 🍒🎶 Best cartoon collection'),
            _yt('d3ggLDjRJ3Y', 'Masha and the Bear 2026 🎬 NEW EPISODE! 💪 Be in the Pink! 👩‍⚕️💖 Best cartoon collection'),
          ],
        ),
        _channel(
          id: 'mansour',
          title: 'منصور',
          order: 42,
          color: 0xFF5C6BC0,
          playlist: _uploadsOf('UCqiIbqnJB0AVTg6Z6QnZNdw'),
          videos: [
            _yt('TohnJvGq-cU', 'مغامرات منصور — مغامرات مشوقة الجزء 7'),
            _yt('A1edNxaVICE', 'مغامرات منصور — مغامرات مشوقة الجزء 6'),
            _yt('T1AlwoEdxGo', 'مغامرات منصور — مغامرات مشوقة الجزء 5'),
            _yt('l5LwMtanIg8', 'مغامرات منصور — مغامرات مشوقة الجزء 4'),
            _yt('qbrHu-vkXiI', 'مغامرات منصور — الحلقات المميزة ج7'),
            _yt('FdUVdcfsHzY', 'مغامرات منصور — حلقات الاختراعات'),
            _yt('dXeBoTInNcA', 'مغامرات منصور — العطلة مع منصور ج17'),
            _yt('bJpAuVrcQgc', 'مغامرات منصور — جمعتنا مع منصور ج4'),
            _yt('fpfSHyyhD2Q', 'مغامرات منصور — جمعتنا مع منصور ج12'),
            _yt('WcqNNCEFIe0', 'مغامرات منصور | مغامرات مشوقة الجزء 8'),
            _yt('KmJQzvj3FIg', 'هل تصل الرسالة في الوقت المناسب؟ 📮| مغامرات منصور'),
            _yt('LqmH0eN3K6o', 'لا تنظر للأسفل! 😱| مغامرات منصور'),
            _yt('2swheGNdkxg', 'أخطر سحلية في العالم! 🦎🔥| مغامرات منصور'),
            _yt('WNI0q28dc1o', 'من هو اللص؟ لغز محير! 🕵️‍♂️| مغامرات منصور'),
            _yt('abP5NLizwgA', 'مخلوق غامض في الغابة!  🌳😱 | مغامرات منصور'),
            _yt('dwcsOc2Q_6Y', 'سر المها الذهبي… حقيقة أم خيال؟ 🦌✨| مغامرات منصور'),
            _yt('8K-Fgy8aGeg', 'مغامرات منصور | مغامرات مشوقة الجزء 3'),
            _yt('Q_5glqYaiRU', 'هل وحش لوخ نيس حقيقي؟ 🐉🌊| مغامرات منصور'),
            _yt('hPGNGjEy1PM', 'ثلج في الصيف؟ شيء غريب يحدث! ❄️😳| مغامرات منصور'),
          ],
        ),
        _channel(
          id: 'maruko',
          title: 'ماروكو الصغيرة',
          order: 43,
          color: 0xFFEC407A,
          sourceType: SourceType.youtubeVideoList,
          videos: [
            _yt('7Xf9nKYyAM4', 'شارة العمل — ماروكو الصغيرة | سبيستون'),
            _yt('OMbPlfL2VMY', 'الحلقات الثلاث الأولى — ماروكو الصغيرة | سبيستون'),
            _yt('vnwWjLlbYUQ', 'المقدمة الرسمية — ماروكو الصغيرة'),
            _yt('_WgvHPmMYXo', 'مشاجرة الأختين — ماروكو الصغيرة'),
            _yt('zZAQztwJGxg', 'بيع الساعة — ماروكو الصغيرة'),
            _yt('3iKlvWdgQ2M', 'ماروكو الصغيرة تستغل الفرصة'),
            _yt('KQidxkPZrOI', 'عالية مكانتي — ماروكو الصغيرة'),
            _yt('OBPi512Q-0c', 'ماروكو الصغيرة واكتشافها'),
            _yt('efoYDgyUdbU', 'ماروكو الصغيرة والتنظيف'),
            _yt('daBmNllqeto', 'ماروكو الصغيرة والمكالمة الهاتفية'),
            _yt('zT0VZaaXVgg', 'ماروكو الصغيرة وصراحتها الزائدة'),
            _yt('EM4vPYt7t-A', 'ماروكو والهدوء الذي لا ينتهي | سبيستون غو'),
            _yt('BCYkBHqnN0I', 'مغامرات ماروكو مع العائلة | سبيستون غو'),
            _yt('STo24SNg2Ws', 'ماروكو واختبار الرياضيات | سبيستون غو'),
            _yt('0gAG-rxdX2I', 'حرب البلابل — ماروكو الصغيرة | سبيستون غو'),
            _yt('zZcU-kPRorc', 'ماروكو في نظر الجد | سبيستون غو'),
            _yt('ZIuKvaoPd9s', 'Chibi Maruko Chan Eng Dub #812  "I Feel Blue on a Parents\' Visiting Day" and the other'),
            _yt('7y_MQlpWhTI', 'Chibi Maruko Chan Eng Dub #810 "Maruko Learns English Conversation from Hanawa-kun" and…'),
            _yt('oByBTwRovRY', 'ماروكو الصغيرة'),
            _yt('087XUZedVIM', 'ماروكا كصت شعرها'),
            _yt('voB1r9O5iyA', 'ماروكو الصغيرة | ضحك وحنين في كل حلقة! أنمي الطفولة اللي ما ننساه 🥰'),
            _yt('f9kdFpMfhNM', 'ماروكو الصغيره 🤣💖/فعلاً أنها الحقيقة 🙂💖'),
            _yt('jJpb96KqtIo', 'ماروكو الصغيرة .. وعد الأصدقاء .. فيلم جديد هيرجعنا لأيام زمان'),
            _yt('0XzjemCahyY', 'مقابلة حصرية تجمع أيقونة عالم الأنمي ماروكو مع مجلة ذوق | 10 أسئلة مع ماروكو ✨'),
            _yt('Neym6pdqbgg', 'مدينة ماروكو في اليابان | دخلت بيت ماروكو 🤩'),
            _yt('lSnySnVFqw0', 'ماروكو الصغيرة الحلقة 2المقطع1'),
          ],
        ),
        _channel(
          id: 'live_makkah',
          title: 'قرآن للنوم ورقية',
          order: 44,
          color: 0xFF2E7D32,
          sourceType: SourceType.youtubeVideoList,
          videos: [
            _yt('UMT2RvaOKrg', 'قرآن للنوم — جزء عم | شاشة سوداء'),
            _yt('vfdU0VNJvJ0', 'جزء عم — ماهر المعيقلي | شاشة سوداء'),
            _yt('WX2K1q0G9I4', 'سورة الملك للنوم — عمر هشام | شاشة سوداء'),
            _yt('cEDlcpgBCMM', 'سورة الملك — ماهر المعيقلي | شاشة سوداء'),
            _yt('SyYV7OVStLA', 'سورة الملك — مشاري العفاسي | شاشة سوداء'),
            _yt('Nne9H-3Z-bM', 'سورة البقرة — ماهر المعيقلي | شاشة سوداء'),
            _yt('HMAJn52hQqw', 'سورة البقرة كاملة — ماهر المعيقلي | شاشة سوداء'),
            _yt('WFnpX2yMRK8', 'رقية المنزل — تحصين البيت والأولاد'),
            _yt('Jkgu5vGjJz8', 'رقية البيت — البقرة وماهر المعيقلي'),
            _yt('BhtzXGiPB5Y', 'رقية للبيت — سور مباركة'),
            _yt('i4tggpG4rFI', 'الرقية الشرعية — ماهر المعيقلي'),
            _yt('XmJu7Efsj0Y', 'الرقية الشرعية الشاملة — صوت هادئ'),
            _yt('6hDV4sQiQNc', 'رقية شرعية للنوم — ماهر المعيقلي | شاشة سوداء'),
            _yt('5v-P7gbDK9s', 'رقية شرعية شاشة سوداء — ماهر المعيقلي'),
            _yt('pUB-8mMyOPM', 'رقية النوم💚 للمساعدة على النوم بسهولة وعمق😌🎧  best soothing Quran recitation for sleep'),
            _yt('syFIj2-cQC4', 'قران كريم بصوت جميل جدا قبل النوم 😌 راحة نفسية لا توصف 🎧 Quran Recitation'),
            _yt('Z2YwrmCUpCc', 'قرآن كريم للمساعدة على النوم والراحة النفسية ♥️ أرح سمعك وقلبك 🎧'),
            _yt('ny-obqb3p3o', 'قرآن كريم قبل النوم صوت هادئ راحة لا توصف(أزح هموم قلبك)💚استمع بنية الرزق والشفاء بإذن…'),
            _yt('vORTgckbjEU', 'قران كريم بصوت جميل جدا قبل النوم 😌 راحة نفسية لا توصف 🎧 Quran Recitation 1'),
            _yt('KndUuRIGUVY', '[ وَيَقُولُ الْإِنسَانُ أَإِذَا مَا مِتُّ ] | [ تلاوة هادئة تريح القلب ] | [ عبدالله ال…'),
            _yt('Hvh1uOE2-pM', 'قرآن كريم بصوت جميل جدا لنوم هادي 😌 هزاع البلوشي ارح سمعك وقلبك ♥️ راحة نفسية و تلاوة خ…'),
            _yt('Fj0iEdnZI-g', 'قرآن كريم للمساعدة على نوم عميق وبسرعة - قران كريم بصوت جميل جدا جدا قبل النوم 😌 أحمد ا…'),
            _yt('cvScckR3tSY', 'تلاوة هادئة للقرآن لراحة القلوب ❤️ Beautiful Quran Recitation ❤️ #المصحف #اكسبلور'),
            _yt('KWhVVdd19Gw', 'الرقية الشرعية لعلاج الأرق والنوم بهدوء وراحة وسكينة 😌🎧  اجمل تلاوة قران كريم💚 أيوب مصعب'),
            _yt('TQ9R8-TIdV4', 'قرآن هادئ للنوم — 10 ساعات | شاشة سوداء'),
            _yt('kXZgeu27BOo', 'قرآن للنوم — 10 ساعات | شاشة سوداء'),
            _yt('HOREcsKsjcU', 'سورة الملك مكررة — شاشة سوداء'),
            _yt('XqOhVxvooTY', 'رقية للبيت — عبد الرحمن السديس'),
            _yt('zVLxK5Kn6mE', 'رقية العين والحسد — شاشة سوداء'),
            _yt('An3yLxvBEfI', 'الرقية الشرعية للأطفال لنوم هادئ 💛 علاج البكاء والخوف والكوابيس لنوم عميق بإذن الله'),
            _yt('vLlUfUEvKsw', 'الرقية الشرعية للأطفال لنوم هادئ 💛 الحل لعلاج البكاء والخوف والقلق والكوابيس بإذن الله'),
            _yt('qJ97rLdwBR4', 'الرقية الشرعية للأطفال لنوم هادئ 💛 لعلاج البكاء والخوف والكوابيس بإذن الله'),
            _yt('cMdV6fiUTOk', 'رقية شرعية للأطفال قبل النوم | علاج البكاء المتكرر والخوف والعين والحسد بالقرآن الكريم'),
            _yt('ywhTNRaKmXA', 'رقية شرعية للأطفال من العين والحسد والخوف 🤍 شفاء وطمأنينة بالقرآن الكريم ونوم هادئ للصغار'),
            _yt('e2bAhB8dHaQ', 'الرقية الشرعية للأطفال قبل النوم 💛 لعلاج البكاء المستمر والخوف والفزع والعين والسحر بإذ…'),
            _yt('q9j48QtSlus', 'أعظم آية في القرآن 😍💞 آية الكرسي 🌨️ بصوت إسلام صبحي 🌿 ارح سمعك .✅'),
            _yt('fpxO9PF1ous', 'قران كريم بصوت جميل جدا قبل النوم 😌 راحة نفسية لا توصف 🎧 Quran Recitation'),
            _yt('l-ERpWeeVT0', 'قران كريم بصوت جميل جدا جدا قبل النوم 😌🎧 راحة نفسية لا توصف'),
            _yt('g8gtpVqfV_Y', 'قرآن كريم للمساعدة على النوم والراحة النفسية ♥️ أرح سمعك وقلبك🎧 Best Soothing Recitat…'),
            _yt('TpvwktaMBT4', 'رقية هادئة💚الرقية الشرعية للنوم بسهولة للكبار والصغار - best soothing Quran recitation…'),
            _yt('_Jlpyzeniu0', 'رقية النوم🤲لعلاج الارق والنوم والعين والحسد والسحر بصوت يريح القلب جداجدا4'),
          ],
        ),

        _channel(
          id: 'masha_ar',
          title: 'ماشا والدب',
          order: 46,
          color: 0xFFE53935,
          sourceType: SourceType.youtubeVideoList,
          videos: [
            _yt('N9HG6_hdotI', 'ساعة من المرح — ماشا والدب'),
            _yt('b_o6JWdrMB8', 'بيت بالمقلوب — ماشا والدب'),
            _yt('KedRL7GrXo8', 'الحَمَل الجديدة — ماشا والدب'),
            _yt('MZ_nL7BW4Wg', 'الطلاب المثاليون — ماشا والدب'),
            _yt('BmtZ9zo8XYs', 'سباحة أنيقة — ماشا والدب'),
            _yt('FFe8tPNw1AU', 'أكثر 10 حلقات مشاهدة — ماشا والدب'),
            _yt('lF3wFRw1Qa4', 'رحلة الدب — ماشا والدب'),
            _yt('ZYiKqKe4RYc', 'ما أجمل العمل — ماشا والدب'),
            _yt('uXCGuus_U1k', 'يوم الفنون والحِرف — ماشا والدب'),
            _yt('erwBhzx3eok', 'أفضل طريقة لقضاء اليوم — ماشا والدب'),
            _yt('EsGkXt6nneE', 'أميرة الأسنان الحلوة — ماشا والدب'),
            _yt('46V3f4lOzQY', 'سلسلة جديدة 💥 ماشا والدب 👱‍♀️🐻 حلوى الغيوم ☁️🍭 الحلقة 120 📺 كرتون للأطفال'),
            _yt('Fal2JC0QnlI', 'سلسلة جديدة 💥 ماشا والدب 👱‍♀️🐻 جرب، جرب مجدداً 🔨🐵 الحلقة 98 📺 كرتون للأطفال | Masha and…'),
            _yt('H7DjqZkz2Z8', 'ماشا والدب 🐻👱‍♀️ عطلة الثلج ❄️🎄 Masha and the Bear'),
            _yt('FmYG6FAyy_Y', 'مارس 🌸😸 (الحلقة 30) مقتطفات 🐻👱‍♀️ ماشا والدب 🌸😸 Masha and the Bear'),
            _yt('mj6YHRzVlBM', 'ماشا والدب 👱‍♀️🐻 نم يا صغيري 🐺🐑 الحلقة 62 📺 كرتون للأطفال | Masha and the Bear'),
            _yt('cT5CAfDIFIg', 'ماشا والدب 👱‍♀️🐻 الجمال جمال العقل 👩💄 الحلقة 40 📺 كرتون للأطفال | Masha and the Bear'),
            _yt('pj1yaCY7Ees', '💥 سلسلة جديدة 🌟 فليركب الجميع ✨🛥️ ماشا والدب 👱‍♀️ Masha and the Bear'),
            _yt('VNLjdYJXO-4', 'حلقة أصلية 💥 ماشا والدب 🐻👱‍♀️ ضربتان على الرأس تؤلم 👱‍♀️😲 الحلقة 36 📺 كرتون للأطفال'),
            _yt('himl3TJ3Hiw', 'ماشا والدب 🐻👱‍♀️ تشكيلة كبيرة 😊✨ 3 ساعات 🐻👱‍♀️ Masha and the Bear'),
            _yt('x791zcrwQW4', 'ماشا والدب 🐻👱‍♀️ ماشاالغنية VS الفقيرة 👑🐒 Masha and the Bear'),
          ],
        ),
        _channel(
          id: 'blippi_ar',
          title: 'بليبي بالعربي',
          order: 47,
          color: 0xFF039BE5,
          sourceType: SourceType.youtubeVideoList,
          videos: [
            _yt('ZooIBL5z-s8', 'بليبي يزور ملعب داخلي'),
            _yt('fKBp_i03wSE', 'بليبي يزور مصنع للشوكولاتة'),
            _yt('XXyqtYoBXLg', 'بليبي يستكشف حيوانات الغابة'),
            _yt('si138Y1-xs0', 'بلبي يتعلم مهارات السيرك'),
            _yt('JE0MivjUzOc', 'قفزات بلبي على الترامبولين'),
            _yt('uwLH7U-AJ5M', 'سيارات بليبي السريعة'),
            _yt('8CU7aJRXb7U', 'ملعب بلِّيبي الداخلي الملون'),
            _yt('Ng2YGHBVRHw', 'اللعب بالصلصال مع بليبي'),
            _yt('TAs1xWSDgzw', 'بليبي يكتشف سيارات غو كارت'),
            _yt('cLGqn3nnuUk', 'اللعب بالصلصال مع بليبي — طين للأطفال'),
            _yt('wbAxdX2ATgY', 'بليبي يزور حوض سمك | تعلم الحيوانات البحرية | برنامج بليبي التعليمي | Blippi - بليبي با…'),
            _yt('kpkwyrTBKO0', 'بلippi يزور حديقة الحيوانات ويتعلم عن الحيوانات | برنامج بليبي التعليمي | Blippi - بليب…'),
            _yt('VM_5p1Ga2lE', 'بليبي يقفز بالمظلة | برنامج بليبي التعليمي | برامج كرتون و أغاني للأطفال | Blippi'),
            _yt('Zn3qPo5hfOA', 'أغاني للأطفال | بليبي يستكشف سيارة شرطة | برامج كرتون للصغار | Arabic Blippi Explores a…'),
            _yt('C7T4dFUDBjU', '| بليبي يزور ملعب داخلي | برامج و أفلام للصغار  | Arabic Blippi Visits an Indoor Playgr…'),
            _yt('IHpqFYdp9v0', 'متحفُ التاريخِ الطبيعي مع بليبي | Blippi\'s Dinosaurs! | افلام ومسلسلات كرتون واغاني اطفال'),
            _yt('4sZIp-yfdKY', 'بليبي يستكشف سيارة شرطة | برنامج بليبي التعليمي | بليبي بالعربي'),
            _yt('es4Q6dKBqCw', 'مرح بلايبي مع الآيس كريم | برنامج بليبي التعليمي | Blippi\'s Ice Cream Store | Blippi -…'),
            _yt('gciHeFxXPts', 'حلقة المحقق بليبي ++ | بلبي بالعربي | كرتون اطفال و أغاني بليبي للصغار | Blippi Arabic'),
            _yt('5sfTgOpNofM', 'Blippi بالعربي  بلبي يستكشف الحواس الخمسة | افلام كرتون بلبي | العاب اطفال بلي بي | مسلسل'),
          ],
        ),
        _channel(
          id: 'disney_songs',
          title: 'Disney Songs',
          order: 48,
          color: 0xFF5C6BC0,
          sourceType: SourceType.youtubeVideoList,
          videos: [
            _yt('L0MK7qz13bU', 'Let It Go — Sing-Along (Frozen)'),
            _yt('TeQ_TTyLGMs', 'Do You Want to Build a Snowman? — Sing-Along'),
            _yt('kQDw88hEr2c', 'Love Is an Open Door — Sing-Along (Frozen)'),
            _yt('r4KTqce-9Z0', "You're Welcome — Sing-Along (Moana)"),
            _yt('pnZbiKKydWU', "How Far I'll Go — Sing-Along (Moana)"),
            _yt('RTWhvp_OD6s', 'Where You Are — Sing-Along (Moana)'),
            _yt('ILRs2r6lcHY', 'I See the Light — Sing-Along (Tangled)'),
            _yt('0fVcwXbAWtA', 'When Will My Life Begin? — Sing-Along (Tangled)'),
            _yt('YRpvIiz9G8A', "We Don't Talk About Bruno — Sing-Along (Encanto)"),
            _yt('uh4dTLJ9q9o', 'Lava — Official Lyric Video'),
            _yt('6BH-Rxd-NBo', 'The Bare Necessities — Sing-Along (Jungle Book)'),
            _yt('GC_mV1IpjWA', 'Under the Sea — Official Video (Little Mermaid)'),
            _yt('1MPZRcyTrcU', "You've Got a Friend in Me — Toy Story"),
            _yt('0MxulhivCvI', 'Hakuna Matata — The Lion King'),
            _yt('eitDnP0_83k', 'A Whole New World — Aladdin'),
            _yt('bseyU2PvBQo', 'Hot Dog Dance Compilation — Mickey Mouse Clubhouse'),
            _yt('3f0C_PGcTAw', 'Welcome to the Clubhouse (Hot Dog!) — Mickey'),
            _yt('DAb93ws35gA', 'My Friends Tigger & Pooh Theme — Disney Junior'),
            _yt('GibiNy4d4gc', 'Carmen Twillie, Lebo M. - Circle of Life (From "The Lion King")'),
            _yt('nrZxwPwmgrw', 'Idina Menzel, Evan Rachel Wood - Show Yourself (From "Frozen 2"/ Sing-Along)'),
            _yt('bBeZSuHI4Qc', 'Diane Guerrero, Stephanie Beatriz - What Else Can I Do? (From "Encanto")'),
            _yt('79DijItQXMM', 'Dwayne Johnson - You\'re Welcome (from Moana/Official Video)'),
            _yt('cPAbx5kgCJo', 'Auli\'i Cravalho - How Far I\'ll Go (from Moana/Official Video)'),
            _yt('tQwVKr8rCYw', 'Jessica Darrow - Surface Pressure (From "Encanto")'),
            _yt('Dr57W6R1qVE', 'Idina Menzel - Let It Go (from "Frozen") (Sing-Along Version)'),
            _yt('HSosNxNdfR8', 'Disney Junior Songs Compilation 🎶 | Dance with Mickey Mouse, Minnie Mouse & MORE | @dis…'),
            _yt('5Q12W7t2Av4', 'Theme Songs! Compilation | @disneyjr'),
            _yt('sLpv7yMAB3w', 'Fancy Nancy Clancy | Sing Along - Theme Song! 🎶 | Disney Kids'),
          ],
        ),
        _channel(
          id: 'babar',
          title: 'بابار',
          order: 50,
          color: 0xFF78909C,
          sourceType: SourceType.youtubeVideoList,
          videos: [
            _yt('CKG8KXSiehs', 'Babar — The Elephant Express (Ep. 18)'),
            _yt('7x1RmD8gnug', 'Babar — Remember When… (Ep. 26)'),
            _yt('OzjPwN0rDY0', 'Babar — Monkey Business (Ep. 23)'),
            _yt('8lXs1qmACnU', 'Babar — A Tale of Two Siblings (Ep. 36)'),
            _yt('fbRBhg1tegQ', 'Babar — The City of Elephants (Ep. 4)'),
            _yt('tBebJGDwNC0', 'Babar — City Ways (Ep. 2)'),
            _yt('50jU1R3tNMM', "Babar — An Elephant's Best Friend (Ep. 9)"),
            _yt('USYFs3FfPT0', 'Babar — Between Friends (Ep. 16)'),
            _yt('sN52Lm31zDY', "Babar — What's Mine is Mine (Ep. 49)"),
            _yt('IBRWCeWhSGQ', 'Babar — My Dinner with Rataxes (Ep. 33)'),
            _yt('OhGOJoLKOts', 'Babar — Helping Hands (Ep. 54)'),
            _yt(
              '8Z5jvr_JJUk',
              'Babar & Badou — Kite Fight / Zoomerblimps (Ep. 9)',
            ),
            _yt(
              'uilO6OTjo-4',
              'Babar & Badou — The Brave Guy / Starring Ms. Strich (Ep. 14)',
            ),
            _yt(
              'PlKszSbTh1E',
              'Babar & Badou — The Unhidden Courtyard / The Rhino Rule (Ep. 36)',
            ),
            _yt(
              'hoT5HIAhTQ8',
              'Babar & Badou — Fair is Fair / Savanna Surfing (Ep. 55)',
            ),
            _yt(
              'QUkhjd127ho',
              'Babar & Badou — Ruby Rumpus / Dandy Andi (Ep. 17)',
            ),
            _yt(
              'Vl1F5cB8pqE',
              'Babar & Badou — The Thunderclap / Junior Marching Band (Ep. 4)',
            ),
            _yt(
              '_LmXqt73EVA',
              'Babar & Badou — Spy Trap / Sneazles (Ep. 1)',
            ),
            _yt('iqiNjhgTO2Q', 'Babar And The Adventures Of Badou | Tutu Badou/Hidden Courtyard - Ep.  2'),
            _yt('-RCl1vE8NiE', 'Babar And The Adventures Of Badou | Gone Wild/Operation Secret Suitcase - Ep. 10'),
            _yt('-oMd9V9aEbc', 'Babar And The Adventures Of Badou | Spytrap/Sneazles - Ep. 1'),
            _yt('eaf5hYzhVxM', 'Babar And The Adventures Of Badou | Kite Fight/Zoomerblimps - Ep.  9'),
            _yt('hBaS3C_VATs', 'Babar | Babar\'s First Step: Ep. 1'),
            _yt('nbyKuDslLDs', 'Babar | City Ways: Ep. 2'),
            _yt('S8xG06aCnFs', 'Babar | Elephant Express: Ep. 18'),
            _yt('mrtv8d1K1AM', 'Babar | A Pair of Queens: Ep. 42'),
            _yt('FHNVZmPGaoE', 'Babar | Remember When… : Ep. 26'),
          ],
        ),
        _channel(
          id: 'hadikat_almarah',
          title: 'حديقة المرح',
          order: 51,
          color: 0xFFAB47BC,
          sourceType: SourceType.youtubeVideoList,
          videos: [
            _yt('knTqvBZtgDc', 'نظيف نظيف — حديقة المرح | 1'),
            _yt('bGRQ9KBKpwA', 'جوجو — حديقة المرح | 2'),
            _yt('lZKz-xtGLiU', 'الطائرة الظريفة — حديقة المرح | 3'),
            _yt('talSXCgXMJk', 'أواني الزهور — حديقة المرح | 4'),
            _yt('EHCfylJXNto', 'الدمى المضحكة عال — حديقة المرح | 5'),
            _yt('rqmJ3-3kcEg', 'استيقظ إيجل بيجل — حديقة المرح'),
            _yt('DDhMUpA3CuA', 'حجر هوبزا هوب الخاصة — حديقة المرح'),
            _yt('fi1qBp_VNfY', '1 + 2 — حديقة المرح'),
            _yt('oRmgEaQAyQc', 'بطانية — حديقة المرح'),
            _yt('OA7fVAxkuxw', 'إخفاء — حديقة المرح'),
            _yt('9A-Cy0m0NHA', 'حلقة 230 — حديقة المرح'),
            _yt('U6-tRUDmNkE', 'في حديقة الليل - تجميع لمدة ساعتين - العلامة التجارية الجديدة'),
            _yt('v455AZLlV_E', 'فوق وتحت | حديقة المرح - WildBrain | عرض وقت النوم'),
            _yt('Ylc4U3_6Bg8', 'إيغل بيغل يبحث عن أبسي دايزي ويتبع سريرها | حديقة المرح - WildBrain | عرض وقت النوم'),
            _yt('k154IrniqMA', 'عائلة بونتيبين تجد بطانية إيجل بيجل | حديقة المرح - WildBrain | أفلام الأطفال'),
            _yt('gd71x-DarpI', 'حديقة المرح : نظيف نظيف  | 1'),
            _yt('57JyD-ojZZM', 'حديقة المرح : جوجو | 2'),
            _yt('UB0CPBmxbgc', 'حديقة المرح : 1+ 2'),
            _yt('5MF0EY58iq8', 'حديقة المرح   لعب يختبئ مع - ماكا باكا 223'),
            _yt('gzzo03T_FCQ', 'حديقة المرح : بطانية 120'),
            _yt('EUZZDcPtFhk', 'حديقة المرح : 230'),
          ],
        ),
        _channel(
          id: 'minecraft',
          title: 'Minecraft',
          order: 52,
          color: 0xFF7CB342,
          playlist: _dadOliviaMinecraftPlaylist,
          videos: [
            _yt('3prPLWKeDiw', 'Dad And Olivia Play: Minecraft'),
            _yt('FjTATyVGl-o', 'Building our treehouse — Dad & Olivia'),
            _yt('y1pigDzOku0', "What's A Fish House? — Dad & Olivia"),
            _yt('rpZwIU0oZbg', 'Fish Problems — Dad & Olivia'),
            _yt('jeust7nhHdo', 'More Zoo Animals — Dad & Olivia'),
            _yt('O74nJOq3vjw', "We're Back! — Dad & Olivia Minecraft"),
            _yt('vBhSLvba0U8', 'Village Adventure — Dad & Olivia'),
            _yt('aayOk2wVf6w', 'NEW BABIES — Dad & Olivia'),
            _yt('dptgi5L8N7Y', 'Dad & Olivia Plus A Special Guest'),
            _yt('VO0Hf2q2FDY', 'We built our first cabin!'),
            _yt('pyLrc-CIm48', 'Our First Chicken Coop!'),
            _yt('sRPD8kEslRQ', 'Minecraft Makeover: Family Edition'),
            _yt('UVRFH_QIfFA', 'Pool & Barn — Let\'s Play Minecraft'),
            _yt('hp73MXqh0wE', 'Finding Puppies and Building Houses'),
            _yt('RfhUhx1MgS0', 'Building Amazing Villager Shops'),
            _yt('Fo21W_4F5KQ', 'Time To Build New Bases'),
            _yt('K6U_08kLB-E', 'Our New Sheep Farm'),
            _yt('gE8JZLs5xg8', 'How To Find All New Dogs!'),
            _yt('rWHeGjRWTDU', 'OUR CRAFTY WORLD S7E1'),
            _yt('8rJbRLkg7A8', 'Our New Starter Mansions? - S4E1'),
            _yt('u5q-IP6Fri8', 'Building Our Massive Wool Farm Factory - S4E6'),
            _yt('lyWHdvbcfcE', 'The Warden is my friend forever ❤️ #minecraft #gamesforkidshub #warden'),
            _yt('mytR61bJeEs', 'Episode 1: Our first homes in Minecraft!'),
          ],
        ),
    ];
    // Drop blocked titles even from the built-in seed.
    return CatalogSanitize.channels(channels);
  }

  /// Merge newer seed defaults onto an existing catalog without wiping parent toggles.
  static List<ContentChannel> mergeSeedUpdates(List<ContentChannel> existing) {
    // Fold retired رقية وقرآن into قرآن للنوم ورقية before dropping the old tile.
    final absorbedQuran = <VideoItem>[];
    for (final ch in existing) {
      if (ch.id == 'live_quran') {
        absorbedQuran.addAll(ch.videos);
      }
    }

    final byId = {
      for (final ch in existing.where((c) => !retiredChannelIds.contains(c.id)))
        ch.id: ch,
    };

    if (absorbedQuran.isNotEmpty) {
      final hub = byId['live_makkah'];
      if (hub != null) {
        final have = hub.videos.map((v) => v.id).toSet();
        final extra = [
          for (final v in absorbedQuran)
            if (!have.contains(v.id)) v,
        ];
        if (extra.isNotEmpty) {
          byId['live_makkah'] = hub.copyWith(videos: [...hub.videos, ...extra]);
        }
      }
    }

    for (final seedCh in seed()) {
      final current = byId[seedCh.id];
      if (current == null) {
        byId[seedCh.id] = seedCh;
        continue;
      }

      final clearSpacetoonUploads = seedCh.id == 'spacetoon' &&
          (seedCh.youtubePlaylistId == null ||
              seedCh.youtubePlaylistId!.isEmpty) &&
          current.youtubePlaylistId == _spacetoonUploadsPlaylist;

      final needsPlaylist = !current.playlistManagedByParent &&
          (current.youtubePlaylistId == null ||
              current.youtubePlaylistId!.isEmpty) &&
          seedCh.youtubePlaylistId != null &&
          seedCh.youtubePlaylistId!.isNotEmpty &&
          current.videos.isEmpty;
      final replaceNumberblocksPlaylist = seedCh.id == 'numberblocks' &&
          !current.playlistManagedByParent &&
          seedCh.youtubePlaylistId != null &&
          seedCh.youtubePlaylistId!.isNotEmpty &&
          current.youtubePlaylistId != seedCh.youtubePlaylistId;
      final followChanged = !current.playlistManagedByParent &&
          current.followUploads != seedCh.followUploads;

      final dropWrongKidsMusic = seedCh.id == 'kids_music' &&
          current.videos.any((v) => v.id == _retiredKidsMusicVideoId);
      final dropRetiredLive = seedCh.id == 'live_makkah' &&
          current.videos.any((v) => retiredLiveVideoIds.contains(v.id));
      // Keep every existing video (including prior playlist-sync items). Seed
      // upgrades only add missing curated starters — never prune the catalog.
      final baseVideos = [
        for (final v in current.videos)
          if ((!dropWrongKidsMusic || v.id != _retiredKidsMusicVideoId) &&
              (!dropRetiredLive || !retiredLiveVideoIds.contains(v.id)))
            v,
      ];
      final existingIds = baseVideos.map((v) => v.id).toSet();
      final missingVideos =
          seedCh.videos.where((v) => !existingIds.contains(v.id)).toList();
      final titleStale = current.title != seedCh.title &&
          (seedCh.id == 'spacetoon' ||
              clearSpacetoonUploads ||
              seedCh.id == 'live_makkah');
      final disableFromSeed = !seedCh.enabled && current.enabled;

      if (clearSpacetoonUploads ||
          needsPlaylist ||
          replaceNumberblocksPlaylist ||
          followChanged ||
          missingVideos.isNotEmpty ||
          dropWrongKidsMusic ||
          dropRetiredLive ||
          titleStale ||
          disableFromSeed) {
        final List<VideoItem> videos;
        if (clearSpacetoonUploads) {
          videos = seedCh.videos;
        } else if (current.videos.isEmpty && seedCh.videos.isNotEmpty) {
          videos = seedCh.videos;
        } else if (missingVideos.isNotEmpty ||
            dropWrongKidsMusic ||
            dropRetiredLive) {
          videos = [...baseVideos, ...missingVideos];
        } else {
          videos = current.videos;
        }

        byId[seedCh.id] = current.copyWith(
          title: titleStale || clearSpacetoonUploads
              ? seedCh.title
              : current.title,
          youtubePlaylistId: clearSpacetoonUploads
              ? null
              : (needsPlaylist || replaceNumberblocksPlaylist
                  ? seedCh.youtubePlaylistId
                  : current.youtubePlaylistId),
          clearPlaylist: clearSpacetoonUploads,
          videos: videos,
          sourceType: clearSpacetoonUploads ||
                  needsPlaylist ||
                  replaceNumberblocksPlaylist
              ? seedCh.sourceType
              : current.sourceType,
          sortOrder: seedCh.sortOrder,
          color: seedCh.color,
          enabled: !seedCh.enabled ? false : current.enabled,
          followUploads: current.playlistManagedByParent
              ? current.followUploads
              : seedCh.followUploads,
        );
      } else if (current.sortOrder != seedCh.sortOrder ||
          current.color != seedCh.color) {
        byId[seedCh.id] = current.copyWith(
          sortOrder: seedCh.sortOrder,
          color: seedCh.color,
        );
      }
    }

    final merged = byId.values.toList()
      ..sort((a, b) => a.sortOrder.compareTo(b.sortOrder));
    return CatalogSanitize.channels(merged);
  }

  static ContentChannel _channel({
    required String id,
    required String title,
    required int order,
    required int color,
    String? playlist,
    SourceType? sourceType,
    List<VideoItem> videos = const [],
    bool enabled = true,
    bool followUploads = false,
  }) {
    return ContentChannel(
      id: id,
      title: title,
      sourceType: sourceType ??
          (playlist != null
              ? SourceType.youtubePlaylist
              : SourceType.youtubeVideoList),
      enabled: enabled,
      youtubePlaylistId: playlist,
      videos: videos,
      sortOrder: order,
      color: color,
      followUploads: followUploads,
    );
  }

  static String _uploadsOf(String channelId) =>
      channelId.startsWith('UC') ? 'UU${channelId.substring(2)}' : channelId;

  static VideoItem _yt(String id, String title) => VideoItem(
        id: id,
        title: title,
        youtubeVideoId: id,
        thumbnailUrl: 'https://i.ytimg.com/vi/$id/hqdefault.jpg',
      );
}
