plugins {
    id 'com.android.application'
}

android {
    namespace 'ae.kidstv.launcher'
    compileSdk 35

    defaultConfig {
        applicationId 'ae.kidstv.launcher'
        minSdk 23
        targetSdk 35
        versionCode 3
        versionName '0.3.0-secure'
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    testOptions {
        unitTests.includeAndroidResources = false
    }
}

dependencies {
    testImplementation 'junit:junit:4.13.2'
}
